/* Resume + site data. Single source of truth. */

window.SITE_DATA = {
  profile: {
    name: "Geoffrey Miller",
    handle: "geoff.e.miller",
    tagline: "Principal Cloud Architect × Agentic AI Engineer",
    location: "Phoenix, AZ",
    email: "Geoff.E.Miller@gmail.com",
    phone: "(480) 688-7370",
    links: {
      site: "geoffmiller.cloud",
      github: "github.com/GeoffMillerAZ",
      linkedin: "linkedin.com/in/geoff-e-miller",
    },
    summary: {
      leadership: "Infrastructure Director and Principal Cloud Architect with 12 years designing and operating cloud platforms at regulated FinTechs (20 years in IT). Builds high-performing platform teams, manages stakeholders across business and technology, and ships simple repeatable engineering patterns that cut spend 30%+ while tightening compliance.",
      cloud: "Principal Cloud Architect specializing in AWS, Kubernetes, and the CNCF ecosystem. Known for unified platform services, policy-as-code, and FinOps automation — real-time, event-driven right-sizing that trims 30–70% off cloud bills without touching reliability.",
      ai: "Level-4 Agentic Software Engineering leader. Ships controlled agentic layers — MCP servers, patterned agents, automated verification with competing incentives — that triple developer throughput while keeping security, compliance, and consistency airtight. Also: a Director and Principal Cloud Architect with 12 years of infrastructure depth to ground the AI in reality.",
    },
  },

  /* ---------- Personas ---------- */
  personas: [
    { id: "ai",         label: "Agentic AI Engineer",       icon: "sparkles" },
    { id: "cloud",      label: "Cloud Architect",           icon: "cloud" },
    { id: "leadership", label: "Technology Leadership",     icon: "compass" },
  ],

  /* ---------- Skill groups, weighted per persona ---------- */
  skillGroups: [
    {
      id: "ai", title: "Agentic AI & MCP",
      weights: { ai: 3, cloud: 1, leadership: 2 },
      skills: ["MCP Servers", "Claude Code", "OpenAI Codex", "Anthropic Agents", "AutoGen", "CrewAI", "Multi-Agent Orchestration", "Prompt Engineering", "Patterned Agents", "Agentic Verification", "MLOps", "Pydantic", "CUE / Cuelang"],
    },
    {
      id: "platform", title: "Platform & Kubernetes",
      weights: { ai: 2, cloud: 3, leadership: 2 },
      skills: ["Amazon EKS", "Kubernetes", "Helm", "Kustomize", "Karpenter", "KEDA", "Istio", "Cilium", "Argo CD", "Flux CD", "GitOps", "Backstage IDP", "Devbox", "NixOS"],
    },
    {
      id: "iac", title: "IaC & Policy-as-Code",
      weights: { ai: 2, cloud: 3, leadership: 2 },
      skills: ["Terraform", "Pulumi", "Crossplane", "OPA / Gatekeeper", "Kyverno", "Sentinel", "CloudFormation", "Packer", "Timoni"],
    },
    {
      id: "aws", title: "AWS Services",
      weights: { ai: 1, cloud: 3, leadership: 2 },
      skills: ["EKS", "Lambda", "Transit Gateway", "Direct Connect", "Route 53", "S3 / Glacier", "DynamoDB", "Aurora", "CloudFront", "Organizations", "Security Hub", "Config"],
    },
    {
      id: "finops", title: "FinOps & SRE",
      weights: { ai: 1, cloud: 3, leadership: 3 },
      skills: ["Savings Plans", "Reserved Instances", "Spot", "Right-sizing Automation", "SLI / SLO", "Error Budgets", "Incident Response", "PagerDuty", "Prometheus", "Grafana", "Datadog", "OpenTelemetry"],
    },
    {
      id: "sec", title: "Security & Compliance",
      weights: { ai: 1, cloud: 2, leadership: 3 },
      skills: ["FFIEC", "PCI-DSS", "SOC 2", "Zero Trust", "CIS Benchmarks", "Snyk", "Falco", "Aqua", "OWASP", "Network Segmentation", "Secrets Management"],
    },
    {
      id: "lead", title: "Leadership",
      weights: { ai: 2, cloud: 2, leadership: 3 },
      skills: ["Team Building", "Stakeholder Management", "Executive Communication", "Mentoring", "Cloud Strategy", "Change Leadership", "Community of Practice"],
    },
  ],

  /* ---------- Roles / timeline ---------- */
  roles: [
    {
      id: "paypal",
      company: "PayPal",
      title: "Sr Engineering Manager, SRE",
      location: "Scottsdale, AZ · Hybrid",
      start: "Oct 2025", end: "Present",
      tagline: "Leading agentic software engineering for the PayPal Command Center.",
      taglines: {
        ai: "Agentic code review gates, patterned agents, and mostly-automated engineering — live in the PayPal Command Center.",
        cloud: "Real-time incident tooling and IaC for the Command Center that keeps every PayPal brand reliable.",
        leadership: "35 whitepapers from 12 post-incident reviews; consulted across every PayPal brand on reliability.",
      },
      scope: ["SRE", "Agentic Engineering", "Incident Management"],
      personaFit: { ai: 3, cloud: 2, leadership: 3 },
      bullets: [
        { tag: "ai",        text: "Lead and specialize in agentic software engineering — mostly-automated dev with controlled approval gates." },
        { tag: "ai",        text: "Ship agentic code & configuration reviewing tools with automatic approval recommendation gates for the Command Center." },
        { tag: "sre",       text: "Built real-time incident management and collaboration tooling that speeds up live incident recovery." },
        { tag: "sre",       text: "Built a risk inventory system mapping mitigation capabilities and auditing reliability readiness across all PayPal brands and workloads." },
        { tag: "sre",       text: "Command Center scheduling + live staffing with low-coverage alarms and daily shift-handoff summarization." },
        { tag: "sre",       text: "Readiness scenario simulations — live P1 drills and paging readiness drills." },
        { tag: "lead",      text: "Authored 35 whitepapers across 12 post-incident reviews with detailed actionable recommendations." },
        { tag: "lead",      text: "Consult across all PayPal brands on cloud architecture, DevOps, and reliability engineering." },
      ],
      impact: {
        type: "dashboard",
        stats: [
          { label: "Post-incident whitepapers", value: "35", unit: "", sub: "across 12 PIRs" },
          { label: "PayPal brands consulted", value: "ALL", unit: "", sub: "cross-brand reliability" },
          { label: "Agentic review gates", value: "Auto", unit: "", sub: "config + IaC approval" },
        ],
        diagram: "commandcenter",
      },
    },
    {
      id: "fcb",
      company: "First Citizens Bank",
      title: "Director of Cloud Infrastructure",
      location: "Remote from Tempe, AZ",
      start: "Jul 2021", end: "Sep 2025",
      tagline: "Built a bank-hardened AWS platform across 100+ accounts; cut spend 30% YoY.",
      taglines: {
        ai: "Sat on the bank's AI governance board — built the guardrails that let GenAI ship inside a bank.",
        cloud: "Bank-hardened AWS platform: 100+ accounts, sub-5ms hybrid connectivity, EKS with zero-day patching.",
        leadership: "Led a 12-person platform team through the SVB → FCB integration; founded the Cloud Community of Practice.",
      },
      scope: ["Landing Zone", "EKS Platform", "FinOps", "AI Governance"],
      personaFit: { ai: 2, cloud: 3, leadership: 3 },
      bullets: [
        { tag: "lead",   text: "Guided the team through the Silicon Valley Bank → First Citizens Bank integration, including platform migrations." },
        { tag: "cloud",  text: "Built secure AWS Landing Zone (100+ accounts) with centralized logging and IAM federation." },
        { tag: "finops", text: "Cut AWS spend 30% YoY via FinOps dashboards and automated rightsizing." },
        { tag: "sec",    text: "Enforced policy-as-code gates for continuous FFIEC / PCI-DSS / SOC 2 compliance." },
        { tag: "cloud",  text: "Designed sub-5 ms hybrid connectivity (Direct Connect, ExpressRoute, Megaport)." },
        { tag: "lead",   text: "Led and mentored a 12-member platform team; founded the Cloud Community of Practice." },
        { tag: "sec",    text: "Integrated DevSecOps toolchain (Sentinel, Snyk, SAST / SCA) into CI/CD." },
        { tag: "sec",    text: "Introduced 'override-as-code' workflow — risk acceptance and governance logic in Git, every exception peer-reviewed." },
        { tag: "platform", text: "Decomposed a monolithic repo into team-owned repos with CODEOWNERS, mandatory gates, and policy-as-code checks. Lead time: 6–12 weeks → days." },
        { tag: "cloud",  text: "Consolidated 'VPC-per-service' sprawl into a shared-services hub (Transit Gateway, Route 53 resolver rules, central interface endpoints) — hundreds of VPCs → a few network segments." },
        { tag: "finops", text: "Replaced thousands of duplicate interface endpoints with a single multi-AZ endpoint hub — VPC-endpoint costs went from top-3 line item to negligible. Saved hundreds of thousands annually." },
        { tag: "platform", text: "Engineered a bank-hardened EKS platform — multi-AZ, CIS-benchmark hardened, OPA/Gatekeeper, automated zero-day node patching." },
        { tag: "ai",     text: "Sat on the bank's AI governance board — crafted secure onboarding patterns for GenAI/ML tools, defined data-access guardrails." },
      ],
      impact: {
        type: "dashboard",
        stats: [
          { label: "AWS spend reduction", value: "30", unit: "%", sub: "year over year" },
          { label: "AWS accounts governed", value: "100+", unit: "", sub: "multi-account landing zone" },
          { label: "Feature lead time", value: "6–12 wk", unit: "→ days", sub: "after monorepo decomposition" },
          { label: "Platform team size", value: "12", unit: "", sub: "direct reports" },
        ],
        chart: {
          kind: "area",
          title: "AWS spend vs workload growth",
          series: [
            { label: "Spend",    color: "var(--neon-pink)", values: [100, 98, 92, 85, 76, 68, 63, 58] },
            { label: "Workload", color: "var(--neon-cyan)", values: [100, 108, 118, 132, 148, 168, 192, 220] },
          ],
          xLabels: ["Q3'21", "Q4", "Q1'22", "Q2", "Q3", "Q4", "Q1'23", "Q2"],
        },
        diagram: "landingzone",
      },
    },
    {
      id: "repay",
      company: "REPAY",
      title: "Director of Cloud Infrastructure",
      location: "Remote from Tempe, AZ",
      start: "Oct 2017", end: "Jul 2021",
      tagline: "Built a green-field AWS platform, passed PCI with zero criticals, grew the team 1 → 18.",
      taglines: {
        ai: "Backstage IDP and docs-as-code — the platform-as-product groundwork for today's agentic patterns.",
        cloud: "Green-field AWS platform that passed PCI with zero criticals; migrations cut from months to a day.",
        leadership: "Grew the infra org from 1 engineer to 18 across SRE, ops, and platform development.",
      },
      scope: ["Green-field AWS", "PCI", "Backstage IDP", "EKS"],
      personaFit: { ai: 1, cloud: 3, leadership: 3 },
      bullets: [
        { tag: "cloud",    text: "Built green-field AWS platform (Terraform, Packer, Kubernetes); passed PCI with zero criticals." },
        { tag: "platform", text: "Launched Backstage IDP and Documentation-as-Code — drift cut 75%, groundwork for everything-as-code." },
        { tag: "lead",     text: "Grew team from a single engineer to a 10-person SRE team + 5-person ops team; led a 3-person full-stack team building platform services." },
        { tag: "sre",      text: "24/7 on-call with PagerDuty; managed enterprise vendor support contracts." },
        { tag: "sre",      text: "Engineered Prometheus / Loki / Grafana observability." },
        { tag: "cloud",    text: "Multi-account Landing Zone with guardrails; FinOps automation saved 30% YoY." },
        { tag: "platform", text: "Secure EKS with GitOps, admission control, and autoscaling." },
        { tag: "platform", text: "Reusable patterns cut cloud migration time from months to one day." },
      ],
      impact: {
        type: "dashboard",
        stats: [
          { label: "PCI audit", value: "0", unit: "criticals", sub: "first-time green-field pass" },
          { label: "Team grown", value: "1 → 18", unit: "", sub: "across SRE, ops, platform dev" },
          { label: "Doc drift", value: "−75", unit: "%", sub: "Documentation-as-Code" },
          { label: "Migration time", value: "months", unit: "→ 1 day", sub: "via reusable patterns" },
        ],
        diagram: "idp",
      },
    },
    {
      id: "ews",
      company: "Early Warning Services",
      title: "DevOps Engineer",
      location: "Scottsdale, AZ",
      start: "Jan 2017", end: "Oct 2017",
      tagline: "Launched Zelle. Scaled to 25M users with zero downtime.",
      scope: ["Launch", "Blue/Green", "Microservices"],
      personaFit: { ai: 0, cloud: 2, leadership: 1 },
      bullets: [
        { tag: "cloud",    text: "Launched Zellepay — large-scale SaaS payments service, 25M users, zero downtime." },
        { tag: "platform", text: "Immutable CI/CD pipelines and containerized microservices — daily releases." },
        { tag: "sre",      text: "Automated blue-green rollouts and A/B tests; RTO under 5 minutes." },
      ],
      impact: {
        type: "stats",
        stats: [
          { label: "Users at launch", value: "25M", unit: "", sub: "Zelle at scale" },
          { label: "Downtime", value: "0", unit: "s", sub: "at public launch" },
          { label: "RTO", value: "< 5", unit: "min", sub: "blue/green rollouts" },
        ],
      },
    },
    {
      id: "thinkvine",
      company: "Thinkvine",
      title: "Principal Cloud Architect",
      location: "Remote from Chandler, AZ",
      start: "Apr 2016", end: "Jan 2017",
      tagline: "Lifted Windows + Linux workloads to AWS. Cut hosting 45%.",
      scope: ["Migration", "Terraform IaC"],
      personaFit: { ai: 0, cloud: 2, leadership: 1 },
      bullets: [
        { tag: "cloud", text: "Migrated Windows & Linux workloads to AWS; cut hosting cost by 45%." },
        { tag: "platform", text: "Converted legacy infra to Terraform IaC with CI/CD — 75% faster deployments." },
      ],
      impact: { type: "stats", stats: [
        { label: "Hosting cost", value: "−45", unit: "%", sub: "post-migration" },
        { label: "Deploys", value: "+75", unit: "% faster", sub: "Terraform IaC + CI/CD" },
      ]},
    },
    {
      id: "ownzones",
      company: "OWNZONES Media Network",
      title: "Lead DevOps Engineer",
      location: "Remote from Scottsdale, AZ",
      start: "Apr 2016", end: "Jul 2016",
      tagline: "Green-field AWS video infra. $300k/yr saved on storage.",
      scope: ["Green-field AWS", "S3 / Glacier"],
      personaFit: { ai: 0, cloud: 2, leadership: 0 },
      bullets: [
        { tag: "cloud", text: "Designed green-field AWS infra; saved USD 300k/yr via S3 lifecycle + Glacier." },
      ],
      impact: { type: "stats", stats: [
        { label: "Storage savings", value: "$300k", unit: "/yr", sub: "S3 lifecycle + Glacier" },
      ]},
    },
    {
      id: "azstate",
      company: "State of Arizona — Dept. of Administration",
      title: "Applications Developer",
      location: "Phoenix, AZ",
      start: "Jan 2015", end: "Apr 2016",
      tagline: "Introduced Git and unit testing to mainframe COBOL.",
      scope: ["Mainframe", "Modernization"],
      personaFit: { ai: 0, cloud: 1, leadership: 1 },
      bullets: [
        { tag: "platform", text: "Introduced Git and automated unit testing to mainframe COBOL systems." },
      ],
      impact: null,
    },
  ],

  education: [
    { school: "Northern Illinois University", degree: "M.S. Computer Science", year: "2015" },
    { school: "Northern Illinois University", degree: "B.S. Computer Science", year: "2013" },
  ],

  certifications: [
    {
      name: "Claude Agentic Architect — Foundations",
      issuer: "Anthropic",
      year: "2026",
      tags: ["Agentic AI", "Claude", "MCP"],
      blurb: "Foundations of designing controlled agentic systems on Claude — patterned agents, MCP servers, verification, and production safety.",
    },
  ],

  /* ---------- Articles ---------- */
  articles: [
    {
      id: "agentic-verification",
      title: "Competing-incentive verification for agentic code factories",
      series: { name: "Level-4 Agentic Engineering", part: 3, of: 5 },
      tags: ["agentic", "verification", "governance"],
      date: "2026-03-18",
      read: "14 min",
      summary: "How to keep a patterned agentic layer honest: pit verifier agents with different incentives against the author agent, then source ground truth external to the source repo.",
    },
    {
      id: "mcp-skills-patterns",
      title: "MCP servers as engineering patterns, not just tools",
      series: { name: "Level-4 Agentic Engineering", part: 2, of: 5 },
      tags: ["mcp", "agentic", "architecture"],
      date: "2026-02-02",
      read: "9 min",
      summary: "Treat MCP capabilities like Kubernetes controllers — declare desired state, let the agent reconcile. Examples in Python with pydantic + CUE.",
    },
    {
      id: "finops-event-driven",
      title: "Event-driven FinOps: 70% cloud spend cut without touching reliability",
      tags: ["finops", "aws", "platform"],
      date: "2026-01-14",
      read: "11 min",
      summary: "Non-prod environments that spin up on first PR comment and tear down on idle. EventBridge rules, tag-driven right-sizing, and the dashboards that prove it.",
    },
    {
      id: "landing-zone-100",
      projectId: "landing-zone",
      title: "The 100-account AWS Landing Zone we run a bank on",
      tags: ["aws", "landing-zone", "ffiec", "pci-dss"],
      date: "2025-11-22",
      read: "16 min",
      summary: "Centralized networking with Transit Gateway, policy-as-code compliance gates, and the onboarding pattern that lets 30+ teams spin up new accounts in an afternoon.",
    },
    {
      id: "override-as-code",
      title: "Override-as-code: every security exception gets a Git commit",
      tags: ["security", "policy-as-code", "governance"],
      date: "2025-09-10",
      read: "7 min",
      summary: "Risk acceptance workflows that auditors love: exceptions carry peer-review, expiration, and automated re-checks. Sample OPA policies included.",
    },
    {
      id: "vpc-endpoint-hub",
      title: "Consolidating VPC endpoints: top-3 line item → negligible",
      tags: ["aws", "finops", "networking"],
      date: "2025-07-04",
      read: "8 min",
      summary: "Thousands of duplicate interface endpoints collapsed into one multi-AZ hub. Traffic analysis, the resolver setup, and the CloudWatch view that caught it.",
    },
    {
      id: "backstage-docs-as-code",
      title: "Cutting documentation drift 75% with Docs-as-Code + Backstage",
      series: { name: "Platform Foundations", part: 1, of: 3 },
      tags: ["backstage", "idp", "docs-as-code"],
      date: "2025-05-19",
      read: "10 min",
      summary: "Docs that ship with code, fail CI when stale, and render inline in Backstage. The pre-commit hooks and the review culture that make it stick.",
    },
    {
      id: "agentic-level4",
      title: "What Level-4 Agentic Software Engineering actually looks like",
      series: { name: "Level-4 Agentic Engineering", part: 1, of: 5 },
      tags: ["agentic", "ai", "strategy"],
      date: "2025-04-02",
      read: "12 min",
      summary: "One stage from full automation: architecture specs in, production-ready software and IaC out. The guardrails, the org change, the verification layer.",
    },
  ],

  /* ---------- Projects ---------- */
  projects: [
    {
      id: "agentic-code-factory",
      roleId: "paypal",
      owner: "org",
      title: "Agentic Code Factory",
      kind: "closed",
      org: "PayPal / First Citizens Bank",
      year: "2024 – present",
      tags: ["agentic", "mcp", "platform"],
      summary: "Independent patterned agentic layer that applies engineering patterns across projects — generates service catalogs, policy code, and IaC with controlled approval gates.",
      problem: "Developer throughput capped by specialization; security and compliance overhead grew linearly with team size.",
      impact: "3× throughput · consistent patterns · automated verification with competing incentives.",
      stack: ["Claude Code", "MCP", "CUE", "Python", "Terraform"],
    },
    {
      id: "landing-zone",
      roleId: "fcb",
      owner: "org",
      title: "100-Account AWS Landing Zone",
      kind: "pro",
      org: "First Citizens Bank",
      year: "2021 – 2025",
      tags: ["aws", "landing-zone", "ffiec", "pci-dss", "soc2"],
      summary: "Multi-account AWS architecture with Transit Gateway, centralized logging, and policy-as-code compliance gates. 30+ dev teams onboard in an afternoon.",
      problem: "Banking workloads required continuous FFIEC / PCI-DSS / SOC 2 compliance across 100+ AWS accounts with no dedicated account-per-team bottleneck.",
      impact: "100+ accounts · 30% YoY spend cut · audit trails zero-cost.",
      stack: ["AWS Organizations", "Transit Gateway", "Terraform", "OPA", "Sentinel"],
    },
    {
      id: "commandcenter-tools",
      roleId: "paypal",
      owner: "org",
      title: "PayPal Command Center Agentic Tooling",
      kind: "closed",
      org: "PayPal",
      year: "2025 – present",
      tags: ["sre", "agentic", "incident-management"],
      summary: "Agentic review gates, risk inventory, readiness drills, and scheduling for the PayPal SRE Command Center.",
      problem: "Command Center reliability readiness was manually audited; incident post-mortems produced reports but weak pattern libraries.",
      impact: "35 whitepapers from 12 PIRs · automated low-coverage alarms · daily shift-handoff summarization.",
      stack: ["Python", "Claude Code", "PagerDuty", "AWS"],
    },
    {
      id: "eks-blueprint",
      roleId: "fcb",
      owner: "org",
      title: "Bank-Hardened EKS Blueprint",
      kind: "pro",
      org: "First Citizens Bank",
      year: "2022 – 2025",
      tags: ["eks", "kubernetes", "cis", "gitops"],
      summary: "Multi-AZ, CIS-benchmark hardened EKS with OPA/Gatekeeper, Karpenter, and automated zero-day node patching.",
      problem: "Regulated workloads on Kubernetes with no tolerance for drift or zero-day exposure.",
      impact: "Zero-day patched within hours · <1% node cost overhead · mandatory-gate compliance.",
      stack: ["EKS", "Karpenter", "Argo CD", "OPA / Gatekeeper", "Kyverno"],
    },
    {
      id: "endpoint-hub",
      roleId: "fcb",
      owner: "org",
      title: "VPC Interface-Endpoint Hub",
      kind: "pro",
      org: "First Citizens Bank",
      year: "2023",
      tags: ["aws", "networking", "finops"],
      summary: "Replaced thousands of duplicate VPC interface endpoints with one multi-AZ endpoint hub via Route 53 resolver rules.",
      problem: "VPC endpoint costs were a top-3 AWS line item despite low utilization per endpoint.",
      impact: "Top-3 line item → negligible · hundreds of thousands saved annually.",
      stack: ["Transit Gateway", "Route 53 Resolver", "Terraform"],
    },
    {
      id: "geoffmiller-cloud",
      owner: "mine",
      title: "geoffmiller.cloud",
      kind: "oss",
      org: "Personal",
      year: "2026",
      tags: ["nextjs", "cuelang", "rag", "tailwind"],
      summary: "This site. A CUE-typed résumé compiled into three persona views, with a JD-aware chat that answers from my background.",
      problem: "Recruiters want one thing: does this candidate fit this JD? Make that question trivial to answer.",
      impact: "Interactive résumé · JD-aware chat · fully open-source reference design.",
      stack: ["Next.js", "Tailwind UI Plus", "CUE", "Anthropic MCP"],
      github: "github.com/GeoffMillerAZ/geoffmiller.cloud",
    },
    {
      id: "override-as-code-oss",
      owner: "mine",
      title: "override-as-code",
      kind: "oss",
      org: "Open Source",
      year: "2024",
      tags: ["opa", "policy-as-code", "governance"],
      summary: "OPA policy pack for git-tracked risk acceptance. Every exception carries expiration, peer-review, and automated re-check.",
      problem: "Security exceptions get rubber-stamped in tickets and forgotten. Auditors hate it.",
      impact: "Audit-ready governance · expiration-driven re-checks · drop-in OPA bundle.",
      stack: ["OPA", "Rego", "GitHub Actions"],
      github: "github.com/GeoffMillerAZ/override-as-code",
    },
  ],

  /* ---------- Achievements ---------- */
  achievements: [
    {
      id: "pir-whitepapers",
      projectId: "commandcenter-tools",
      title: "35 actionable post-incident whitepapers from 12 PIRs",
      metric: "35", metricUnit: "papers", year: "2024 – 2025",
      org: "PayPal", roleId: "paypal",
      tags: ["agentic", "sre", "incident-management"],
      summary: "Built an agentic pipeline that turns the PayPal Command Center's PIRs into a reusable pattern library — not just reports.",
      challenge: "Each post-incident review produced a one-shot Word doc. Patterns repeated, lessons evaporated, and the next on-call read nothing.",
      approach: "Patterned agents extract risk inventory, mitigation checklists, and readiness drills from PIR transcripts; competing-incentive verification cross-checks each whitepaper against incident telemetry before it ships to the library.",
      outcome: "35 whitepapers across 12 incidents, indexed and searchable. Daily shift-handoff summarization on top of the same pipeline.",
      whyItMatters: "Turns operational pain into compounding institutional knowledge — the team gets faster after every outage instead of slower.",
      stack: ["Claude Code", "Python", "PagerDuty", "AWS", "MCP"],
    },
    {
      id: "landing-zone-100",
      projectId: "landing-zone",
      title: "AWS landing zone for 100+ regulated accounts",
      metric: "100+", metricUnit: "accounts", year: "2021 – 2025",
      org: "First Citizens Bank", roleId: "fcb",
      tags: ["aws", "landing-zone", "ffiec", "pci-dss", "soc2"],
      summary: "Multi-account architecture with Transit Gateway, centralized logging, and policy-as-code compliance gates — onboarding 30+ teams in an afternoon.",
      challenge: "Banking workloads required continuous FFIEC / PCI-DSS / SOC 2 compliance with no per-team Ops bottleneck. Account sprawl was already a budget threat.",
      approach: "AWS Organizations + Control Tower with Terraform-driven account vending, OPA/Sentinel guardrails as merge-gate, hub-and-spoke Transit Gateway, and centralized log aggregation. Compliance isn't a phase — it's the default branch.",
      outcome: "100+ accounts governed. New teams onboard in an afternoon. Audit trails generated for free as a byproduct of the platform.",
      whyItMatters: "Made compliance the cheap path. The number that scales linearly with team count is a Terraform PR, not a Ticket-of-Doom.",
      stack: ["AWS Organizations", "Control Tower", "Transit Gateway", "Terraform", "OPA", "Sentinel"],
    },
    {
      id: "finops-30",
      projectId: "endpoint-hub",
      title: "30% YoY AWS spend reduction at a regulated bank",
      metric: "30%", metricUnit: "YoY cut", year: "2022 – 2024",
      org: "First Citizens Bank", roleId: "fcb",
      tags: ["finops", "aws", "platform"],
      summary: "Event-driven FinOps automation that trims waste continuously without touching reliability — including the VPC endpoint hub that killed a top-3 line item.",
      challenge: "AWS spend was growing faster than the workload. Reservation coverage drifted. VPC interface endpoints duplicated thousands of times. No single owner.",
      approach: "Continuous savings-plan optimizer, idle-resource janitor, anomaly alerts wired into Slack, and a Route 53 resolver-based shared endpoint hub that collapsed redundancy. All in IaC, all gated by policy.",
      outcome: "30% YoY reduction. Endpoint hub alone deleted hundreds of thousands of dollars from the bill. Reliability metrics unchanged.",
      whyItMatters: "Proves regulated FinTech can be both compliant and cost-disciplined — the two are usually framed as a tradeoff.",
      stack: ["AWS", "Terraform", "Lambda", "Athena", "Slack"],
    },
    {
      id: "zelle-25m",
      title: "Zelle launch — 25M users, zero downtime",
      metric: "25M", metricUnit: "users", year: "2017",
      org: "Early Warning Services", roleId: "ews",
      tags: ["aws", "platform", "scale"],
      summary: "Engineered the cloud platform that hosted Zelle's launch, scaling from 0 to 25M users without an incident at GA.",
      challenge: "Launch a peer-to-peer payments network for the largest US banks, on day one, against the full traffic of a national rollout — with no fallback plan.",
      approach: "Multi-region active-active AWS architecture, automated chaos drills before launch, capacity headroom modeled per bank-partner activation curve, and a runbook tested under simulated bank-onboarding-stampede conditions.",
      outcome: "Hit 25M users with zero customer-facing downtime at GA. The platform absorbed bank activations as a non-event.",
      whyItMatters: "First-hand proof that bank-grade reliability and modern cloud aren't mutually exclusive — long before that became conventional wisdom.",
      stack: ["AWS", "DynamoDB", "ECS", "Lambda", "SNS"],
    },
    {
      id: "team-1-to-18",
      title: "Built infra org from 1 to 18 — and a 12-person platform team",
      metric: "1 → 18", metricUnit: "engineers", year: "2018 – 2025",
      org: "REPAY · First Citizens Bank", roleId: "repay",
      tags: ["leadership", "platform", "team-building"],
      summary: "Two team-building cycles back-to-back: REPAY infra 1→18, then a 12-person platform team at FCB built from scratch.",
      challenge: "Both orgs needed to scale infra and platform engineering without it becoming an Ops bottleneck — or a hiring bonfire.",
      approach: "Hire for systems-thinking and writing ability, not tool-of-the-week. Run a Community-of-Practice model so platform consumers self-serve. Document patterns until the team is no longer the bottleneck.",
      outcome: "REPAY: 1 → 18 across infra and SRE. FCB: 12-person platform team supporting 30+ product teams across 100+ accounts. Both orgs running on patterns, not heroics.",
      whyItMatters: "The hardest part of platform engineering isn't the platform — it's the org around it. Got to run that play twice.",
      stack: ["Hiring", "CoP model", "Mentorship", "Docs-as-code"],
    },
    {
      id: "pci-greenfield",
      title: "PCI-DSS first-pass green on a green-field stack",
      metric: "0", metricUnit: "criticals", year: "2019",
      org: "REPAY", roleId: "repay",
      tags: ["pci-dss", "security", "platform"],
      summary: "Designed a payments-processing AWS architecture that passed its first PCI-DSS audit with zero criticals — at a company processing billions.",
      challenge: "Build a regulated payments platform that auditors couldn't poke holes in, on a deadline, with a small team.",
      approach: "Network segmentation by control scope, KMS-everywhere, minimal-IAM with break-glass auditing, and IaC that made every control reviewable as a PR diff. Audit prep was exporting the repo.",
      outcome: "First-pass PCI-DSS audit closed with zero criticals. Subsequent audits ran in days, not months.",
      whyItMatters: "Demonstrates the discipline behind 'compliance as code' — when the audit is the side effect of how you build, it stops being a project.",
      stack: ["AWS", "Terraform", "KMS", "VPC", "Cloudtrail"],
    },
    {
      id: "eks-zeroday",
      projectId: "eks-blueprint",
      title: "Bank-hardened EKS — zero-days patched in hours",
      metric: "<4h", metricUnit: "to patch", year: "2022 – 2025",
      org: "First Citizens Bank", roleId: "fcb",
      tags: ["kubernetes", "eks", "security", "cis"],
      summary: "EKS blueprint with CIS-benchmark hardening, OPA/Gatekeeper, Karpenter, and automated zero-day node patching that runs in hours.",
      challenge: "Regulated workloads on Kubernetes, with zero tolerance for drift, vulnerable nodes, or weekend-long patching windows.",
      approach: "Karpenter-driven node lifecycle so patching = re-provisioning, OPA/Gatekeeper + Kyverno as merge-gate, Argo CD for declarative app delivery, immutable AMIs published continuously.",
      outcome: "Zero-days patched in under 4 hours from CVE publication, fleet-wide. Less than 1% node-cost overhead from the safety machinery.",
      whyItMatters: "Lets a bank run modern Kubernetes without trading reliability for speed — the patch story alone makes the platform defensible to security review.",
      stack: ["EKS", "Karpenter", "Argo CD", "OPA / Gatekeeper", "Kyverno"],
    },
    {
      id: "mainframe-to-day",
      title: "Mainframe-to-cloud migrations: months → a day",
      metric: "months → 1d", metricUnit: "lead time", year: "2015 – 2017",
      org: "Arizona DOA · ThinkVine", roleId: "thinkvine",
      tags: ["aws", "iac", "modernization"],
      summary: "Built reusable IaC migration patterns that compressed legacy-to-cloud lift from months to a single day.",
      challenge: "Each new system migration was hand-rolled. State agencies and small teams couldn't afford a multi-month migration per workload.",
      approach: "Templated CloudFormation/Terraform with workload-archetype patterns (batch, web, data) and standardized cutover playbooks. The next migration always started from the previous one — never from scratch.",
      outcome: "Migration lead time collapsed from months to ~1 day for archetype-fitting workloads. Pattern library still echoes in everything I've built since.",
      whyItMatters: "Early proof that infrastructure is a compounding asset — every migration should make the next one cheaper, not just done.",
      stack: ["AWS", "CloudFormation", "Terraform", "Ansible"],
    },
  ],

  /* ---------- Resources ---------- */
  resources: [
    // YouTube
    { kind: "youtube",  title: "Fireship",                 by: "Jeff Delaney",      note: "100-second explainers that get technical quickly." },
    { kind: "youtube",  title: "ThePrimeagen",             by: "Michael Paulson",   note: "Fast code, strong opinions, terminal-first workflows." },
    { kind: "youtube",  title: "Jim Kwik",                 by: "Jim Kwik",          note: "Learning how to learn — foundational for picking up new stacks fast." },
    { kind: "youtube",  title: "HashiCorp",                by: "HashiCorp",         note: "Deep dives on Terraform, Vault, and Consul." },
    // Podcasts
    { kind: "podcast",  title: "Kubernetes Podcast",       by: "Google",            note: "Release breakdowns and community interviews." },
    { kind: "podcast",  title: "Software Engineering Daily", by: "SED",             note: "Long-form engineering conversations — breadth across the field." },
    { kind: "podcast",  title: "Latent Space",             by: "swyx & Alessio",    note: "Applied AI engineering, agentic patterns, and MCP deep-dives." },
    { kind: "podcast",  title: "The Changelog",            by: "Jerod & Adam",      note: "Open source under the hood." },
    // Books
    { kind: "book",     title: "Accelerate",               by: "Forsgren, Humble, Kim", note: "The DORA metrics bible — what actually predicts software delivery performance." },
    { kind: "book",     title: "Team Topologies",          by: "Skelton & Pais",    note: "Conway's Law turned into a team-design playbook." },
    { kind: "book",     title: "Staff Engineer",           by: "Will Larson",       note: "What the IC track looks like above senior." },
    { kind: "book",     title: "The Phoenix Project",      by: "Gene Kim et al.",   note: "DevOps origin story, still the clearest intro." },
    { kind: "book",     title: "An Elegant Puzzle",        by: "Will Larson",       note: "Engineering management as systems design." },
    // Blogs
    { kind: "blog",     title: "lethain.com",              by: "Will Larson",       note: "Weekly essays on engineering leadership." },
    { kind: "blog",     title: "Simon Willison",           by: "simonwillison.net", note: "Daily LLM experimentation — practical, cited, reproducible." },
    { kind: "blog",     title: "Charity Majors",           by: "charity.wtf",       note: "Observability philosophy, hiring, and SRE culture." },
    { kind: "blog",     title: "Last Week in AWS",         by: "Corey Quinn",       note: "FinOps-adjacent AWS news with bite." },
    { kind: "blog",     title: "Anthropic Engineering",    by: "Anthropic",         note: "Applied agent and MCP engineering writeups." },
  ],

  /* ---------- About Me ---------- */
  about: [
    { id: "family",    title: "Dad mode",         body: "Two kids. Most of my weekend build-time is a kid on one knee pointing at which wire goes where.", icon: "users" },
    { id: "bjj",       title: "Brazilian Jiu-Jitsu", body: "White belt energy, permanent. BJJ is the best debugging practice I know — you think your position is great until someone shows you why it isn't.", icon: "shield" },
    { id: "latin",     title: "Latin dancing",    body: "Salsa, Bachata, Merengue, Cha-Cha. It keeps me fluent in a thing that's not keyboard-shaped.", icon: "music" },
    { id: "rc",        title: "RC drones + monster trucks", body: "Anything with a brushless motor and a receiver. I like the tuning loop — telemetry, tweak, fly again. Same loop, smaller stakes.", icon: "drone" },
    { id: "ai",        title: "Tinkering with AI", body: "Nights and weekends: building agentic harnesses, poking MCP servers, wiring small models into weirder workflows. This site is part of that.", icon: "sparkles" },
    { id: "build",     title: "Workshop",         body: "I build and fix things with the kids. No great woodworker, but a lot of time on 'why did that break' conversations — which is most of engineering.", icon: "tool" },
  ],
};
