/* Resume + site data. Single source of truth. */

window.SITE_DATA = {
  profile: {
    name: "Geoffrey Miller",
    handle: "geoff.e.miller",
    tagline: "Principal Cloud Architect × Agentic AI Engineer",
    location: "Phoenix, AZ",
    email: "Geoff.E.Miller@gmail.com",
    phone: "(480) 688-7370",
    links: {
      site: "geoffmiller.cloud",
      github: "github.com/GeoffMillerAZ",
      linkedin: "linkedin.com/in/geoff-e-miller",
    },
    summary: {
      leadership: "Infrastructure Director and Principal Cloud Architect with 12 years designing and operating cloud platforms at regulated FinTechs (20 years in IT). Builds high-performing platform teams, manages stakeholders across business and technology, and ships simple repeatable engineering patterns that cut spend 30%+ while tightening compliance.",
      cloud: "Principal Cloud Architect specializing in AWS, Kubernetes, and the CNCF ecosystem. Known for unified platform services, policy-as-code, and FinOps automation — real-time, event-driven right-sizing that trims 30–70% off cloud bills without touching reliability.",
      ai: "Level-4 Agentic Software Engineering leader. Ships controlled agentic layers — MCP servers, patterned agents, automated verification with competing incentives — that triple developer throughput while keeping security, compliance, and consistency airtight. Also: a Director and Principal Cloud Architect with 12 years of infrastructure depth to ground the AI in reality.",
    },
  },

  /* ---------- Personas ---------- */
  personas: [
    { id: "ai",         label: "Agentic AI Engineer",       icon: "sparkles" },
    { id: "cloud",      label: "Cloud Architect",           icon: "cloud" },
    { id: "leadership", label: "Technology Leadership",     icon: "compass" },
  ],

  /* ---------- Skill groups, weighted per persona ---------- */
  skillGroups: [
    {
      id: "ai", title: "Agentic AI & MCP",
      weights: { ai: 3, cloud: 1, leadership: 2 },
      skills: ["MCP Servers", "Claude Code", "OpenAI Codex", "Anthropic Agents", "AutoGen", "CrewAI", "Multi-Agent Orchestration", "Prompt Engineering", "Patterned Agents", "Agentic Verification", "MLOps", "Pydantic", "CUE / Cuelang"],
    },
    {
      id: "platform", title: "Platform & Kubernetes",
      weights: { ai: 2, cloud: 3, leadership: 2 },
      skills: ["Amazon EKS", "Kubernetes", "Helm", "Kustomize", "Karpenter", "KEDA", "Istio", "Cilium", "Argo CD", "Flux CD", "GitOps", "Backstage IDP", "Devbox", "NixOS"],
    },
    {
      id: "iac", title: "IaC & Policy-as-Code",
      weights: { ai: 2, cloud: 3, leadership: 2 },
      skills: ["Terraform", "Pulumi", "Crossplane", "OPA / Gatekeeper", "Kyverno", "Sentinel", "CloudFormation", "Packer", "Timoni"],
    },
    {
      id: "aws", title: "AWS Services",
      weights: { ai: 1, cloud: 3, leadership: 2 },
      skills: ["EKS", "Lambda", "Transit Gateway", "Direct Connect", "Route 53", "S3 / Glacier", "DynamoDB", "Aurora", "CloudFront", "Organizations", "Security Hub", "Config"],
    },
    {
      id: "finops", title: "FinOps & SRE",
      weights: { ai: 1, cloud: 3, leadership: 3 },
      skills: ["Savings Plans", "Reserved Instances", "Spot", "Right-sizing Automation", "SLI / SLO", "Error Budgets", "Incident Response", "PagerDuty", "Prometheus", "Grafana", "Datadog", "OpenTelemetry"],
    },
    {
      id: "sec", title: "Security & Compliance",
      weights: { ai: 1, cloud: 2, leadership: 3 },
      skills: ["FFIEC", "PCI-DSS", "SOC 2", "Zero Trust", "CIS Benchmarks", "Snyk", "Falco", "Aqua", "OWASP", "Network Segmentation", "Secrets Management"],
    },
    {
      id: "lead", title: "Leadership",
      weights: { ai: 2, cloud: 2, leadership: 3 },
      skills: ["Team Building", "Stakeholder Management", "Executive Communication", "Mentoring", "Cloud Strategy", "Change Leadership", "Community of Practice"],
    },
  ],

  /* ---------- Roles / timeline ---------- */
  roles: [
    {
      id: "paypal",
      company: "PayPal",
      title: "Sr Engineering Manager, SRE",
      location: "Scottsdale, AZ · Hybrid",
      start: "Oct 2025", end: "Present",
      tagline: "Leading agentic software engineering for the PayPal Command Center.",
      taglines: {
        ai: "Agentic code review gates, patterned agents, and mostly-automated engineering — live in the PayPal Command Center.",
        cloud: "Real-time incident tooling and IaC for the Command Center that keeps every PayPal brand reliable.",
        leadership: "Recognized as a top-impact AI user enterprise-wide; consulted across every PayPal brand on reliability and agentic engineering.",
      },
      scope: ["SRE", "Agentic Engineering", "Incident Management"],
      personaFit: { ai: 3, cloud: 2, leadership: 3 },
      bullets: [
        { tag: "ai",        text: "Lead and specialize in agentic software engineering — mostly-automated dev with controlled approval gates." },
        { tag: "ai",        text: "Ship agentic code & configuration reviewing tools with automatic approval recommendation gates for the Command Center." },
        { tag: "sre",       text: "Built real-time incident management and collaboration tooling that speeds up live incident recovery." },
        { tag: "sre",       text: "Built a risk inventory system mapping mitigation capabilities and auditing reliability readiness across all PayPal brands and workloads." },
        { tag: "sre",       text: "Command Center scheduling + live staffing with low-coverage alarms and daily shift-handoff summarization." },
        { tag: "sre",       text: "Readiness scenario simulations — live P1 drills and paging readiness drills." },
        { tag: "lead",      text: "Recognized as a top-impact AI user enterprise-wide and appointed to PayPal's AI Super Users community shaping corporate AI adoption." },
        { tag: "lead",      text: "Authored GameDay tooling that ingests incident logs and chat transcripts to generate agentically-scored participant feedback reports." },
        { tag: "lead",      text: "Consult across all PayPal brands on cloud architecture, DevOps, and reliability engineering." },
      ],
      impact: {
        type: "dashboard",
        stats: [
          { label: "Enterprise AI recognition", value: "Top", unit: "user", sub: "AI Super Users community" },
          { label: "PayPal brands consulted", value: "ALL", unit: "", sub: "cross-brand reliability" },
          { label: "Agentic review gates", value: "Auto", unit: "", sub: "config + IaC approval" },
        ],
        diagram: "commandcenter",
      },
    },
    {
      id: "fcb",
      company: "First Citizens Bank",
      title: "Director of Cloud Infrastructure",
      location: "Remote from Tempe, AZ",
      start: "Jul 2021", end: "Sep 2025",
      tagline: "Built a bank-hardened AWS platform across 100+ accounts; cut spend 30% YoY.",
      taglines: {
        ai: "Sat on the bank's AI governance board — built the guardrails that let GenAI ship inside a bank.",
        cloud: "Bank-hardened AWS platform: 100+ accounts, sub-5ms hybrid connectivity, EKS with zero-day patching.",
        leadership: "Led a 12-person platform team through the SVB → FCB integration; founded the Cloud Community of Practice.",
      },
      scope: ["Landing Zone", "EKS Platform", "FinOps", "AI Governance"],
      personaFit: { ai: 2, cloud: 3, leadership: 3 },
      bullets: [
        { tag: "lead",   text: "Guided the team through the Silicon Valley Bank → First Citizens Bank integration, including platform migrations." },
        { tag: "cloud",  text: "Built secure AWS Landing Zone (100+ accounts) with centralized logging and IAM federation." },
        { tag: "finops", text: "Cut AWS spend 30% YoY via FinOps dashboards and automated rightsizing." },
        { tag: "sec",    text: "Enforced policy-as-code gates for continuous FFIEC / PCI-DSS / SOC 2 compliance." },
        { tag: "cloud",  text: "Designed sub-5 ms hybrid connectivity (Direct Connect, ExpressRoute, Megaport)." },
        { tag: "lead",   text: "Led and mentored a 12-member platform team; founded the Cloud Community of Practice." },
        { tag: "sec",    text: "Integrated DevSecOps toolchain (Sentinel, Snyk, SAST / SCA) into CI/CD." },
        { tag: "sec",    text: "Introduced 'override-as-code' workflow — risk acceptance and governance logic in Git, every exception peer-reviewed." },
        { tag: "platform", text: "Decomposed a monolithic repo into team-owned repos with CODEOWNERS, mandatory gates, and policy-as-code checks. Lead time: 6–12 weeks → days." },
        { tag: "cloud",  text: "Consolidated 'VPC-per-service' sprawl into a shared-services hub (Transit Gateway, Route 53 resolver rules, central interface endpoints) — hundreds of VPCs → a few network segments." },
        { tag: "finops", text: "Replaced thousands of duplicate interface endpoints with a single multi-AZ endpoint hub — VPC-endpoint costs went from top-3 line item to negligible. Saved hundreds of thousands annually." },
        { tag: "platform", text: "Engineered a bank-hardened EKS platform — multi-AZ, CIS-benchmark hardened, OPA/Gatekeeper, automated zero-day node patching." },
        { tag: "ai",     text: "Sat on the bank's AI governance board — crafted secure onboarding patterns for GenAI/ML tools, defined data-access guardrails." },
      ],
      impact: {
        type: "dashboard",
        stats: [
          { label: "AWS spend reduction", value: "30", unit: "%", sub: "year over year" },
          { label: "AWS accounts governed", value: "100+", unit: "", sub: "multi-account landing zone" },
          { label: "Feature lead time", value: "6–12 wk", unit: "→ days", sub: "after monorepo decomposition" },
          { label: "Platform team size", value: "12", unit: "", sub: "direct reports" },
        ],
        chart: {
          kind: "area",
          title: "AWS spend vs workload growth",
          series: [
            { label: "Spend",    color: "var(--neon-pink)", values: [100, 98, 92, 85, 76, 68, 63, 58] },
            { label: "Workload", color: "var(--neon-cyan)", values: [100, 108, 118, 132, 148, 168, 192, 220] },
          ],
          xLabels: ["Q3'21", "Q4", "Q1'22", "Q2", "Q3", "Q4", "Q1'23", "Q2"],
        },
        diagram: "landingzone",
      },
    },
    {
      id: "repay",
      company: "REPAY",
      title: "Director of Cloud Infrastructure",
      location: "Remote from Tempe, AZ",
      start: "Oct 2017", end: "Jul 2021",
      tagline: "Built a green-field AWS platform, passed PCI with zero criticals, grew the team 1 → 18.",
      taglines: {
        ai: "Backstage IDP and docs-as-code — the platform-as-product groundwork for today's agentic patterns.",
        cloud: "Green-field AWS platform that passed PCI with zero criticals; migrations cut from months to a day.",
        leadership: "Grew the infra org from 1 engineer to 18 across SRE, ops, and platform development.",
      },
      scope: ["Green-field AWS", "PCI", "Backstage IDP", "EKS"],
      personaFit: { ai: 1, cloud: 3, leadership: 3 },
      bullets: [
        { tag: "cloud",    text: "Built green-field AWS platform (Terraform, Packer, Kubernetes); passed PCI with zero criticals." },
        { tag: "platform", text: "Launched Backstage IDP and Documentation-as-Code — drift cut 75%, groundwork for everything-as-code." },
        { tag: "lead",     text: "Grew team from a single engineer to a 10-person SRE team + 5-person ops team; led a 3-person full-stack team building platform services." },
        { tag: "sre",      text: "24/7 on-call with PagerDuty; managed enterprise vendor support contracts." },
        { tag: "sre",      text: "Engineered Prometheus / Loki / Grafana observability." },
        { tag: "cloud",    text: "Multi-account Landing Zone with guardrails; FinOps automation saved 30% YoY." },
        { tag: "platform", text: "Secure EKS with GitOps, admission control, and autoscaling." },
        { tag: "platform", text: "Reusable patterns cut cloud migration time from months to one day." },
      ],
      impact: {
        type: "dashboard",
        stats: [
          { label: "PCI audit", value: "0", unit: "criticals", sub: "first-time green-field pass" },
          { label: "Team grown", value: "1 → 18", unit: "", sub: "across SRE, ops, platform dev" },
          { label: "Doc drift", value: "−75", unit: "%", sub: "Documentation-as-Code" },
          { label: "Migration time", value: "months", unit: "→ 1 day", sub: "via reusable patterns" },
        ],
        diagram: "idp",
      },
    },
    {
      id: "ews",
      company: "Early Warning Services",
      title: "DevOps Engineer",
      location: "Scottsdale, AZ",
      start: "Jan 2017", end: "Oct 2017",
      tagline: "DevOps engineering at the bank-owned network behind Zelle, during its launch era.",
      scope: ["CI/CD", "Blue/Green", "Microservices"],
      personaFit: { ai: 0, cloud: 2, leadership: 1 },
      bullets: [
        { tag: "cloud",    text: "DevOps engineering at Early Warning Services — the bank-owned network that operates Zelle — during the launch period." },
        { tag: "platform", text: "Built immutable CI/CD pipelines and containerized microservices supporting daily releases." },
        { tag: "sre",      text: "Automated blue-green rollouts and A/B testing to make deploys low-risk." },
      ],
      impact: null,
    },
    {
      id: "thinkvine",
      company: "Thinkvine",
      title: "Principal Cloud Architect",
      location: "Remote from Chandler, AZ",
      start: "Apr 2016", end: "Jan 2017",
      tagline: "Migrated Windows + Linux workloads to AWS with Terraform IaC and CI/CD.",
      scope: ["Migration", "Terraform IaC"],
      personaFit: { ai: 0, cloud: 2, leadership: 1 },
      bullets: [
        { tag: "cloud", text: "Migrated Windows & Linux workloads to AWS, reducing hosting cost." },
        { tag: "platform", text: "Converted legacy infrastructure to Terraform IaC with CI/CD for faster, repeatable deployments." },
      ],
      impact: null,
    },
    {
      id: "ownzones",
      company: "OWNZONES Media Network",
      title: "Lead DevOps Engineer",
      location: "Remote from Scottsdale, AZ",
      start: "Apr 2016", end: "Jul 2016",
      tagline: "Green-field AWS video infrastructure with S3 lifecycle + Glacier cost optimization.",
      scope: ["Green-field AWS", "S3 / Glacier"],
      personaFit: { ai: 0, cloud: 2, leadership: 0 },
      bullets: [
        { tag: "cloud", text: "Designed green-field AWS infrastructure for video workloads, using S3 lifecycle policies and Glacier to optimize storage cost." },
      ],
      impact: null,
    },
    {
      id: "azstate",
      company: "State of Arizona — Dept. of Administration",
      title: "Applications Developer",
      location: "Phoenix, AZ",
      start: "Jan 2015", end: "Apr 2016",
      tagline: "Introduced Git and unit testing to mainframe COBOL.",
      scope: ["Mainframe", "Modernization"],
      personaFit: { ai: 0, cloud: 1, leadership: 1 },
      bullets: [
        { tag: "platform", text: "Introduced Git and automated unit testing to mainframe COBOL systems." },
      ],
      impact: null,
    },
  ],

  education: [
    {
      school: "Northern Illinois University",
      degree: "M.S. Computer Science",
      year: "2015",
      honors: "Emphasis: Network Programming & Database Systems",
    },
    {
      school: "Northern Illinois University",
      degree: "B.S. Computer Science",
      year: "2013",
      honors: "Magna Cum Laude · 3.75 GPA · Upper Division Honors",
    },
  ],

  certifications: [
    {
      name: "Claude Certified Architect — Foundations",
      issuer: "Anthropic",
      year: "In Progress",
      tags: ["Agentic AI", "Claude", "MCP"],
      blurb: "Foundations of designing controlled agentic systems on Claude — patterned agents, MCP servers, verification, and production safety. Currently in progress.",
    },
  ],

  /* ---------- Articles ---------- */
  articles: [
    {
      id: "why-agentic-kit",
      title: "Why every serious team needs an agentic-kit",
      series: { name: "Building the Agentic Stack", part: 1, of: 4 },
      tags: ["agentic", "governance", "platform"],
      date: "2026-06-12",
      read: "11 min",
      summary: "Raw LLM calls are not an engineering platform. An agentic-kit is the governed harness that sits between your agents and production: budget guards, injection detection, replay-tested determinism, competing-incentive verification, and provenance journaling. Without it you have demos; with it you have software you can put in front of a regulated enterprise.",
    },
    {
      id: "why-app-kit-agentic-era",
      title: "The case for an app-kit in the age of agentic coding",
      series: { name: "Building the Agentic Stack", part: 2, of: 4 },
      tags: ["app-kit", "platform", "agentic", "developer-experience"],
      date: "2026-06-10",
      read: "10 min",
      summary: "When agents write most of the code, the scarce resource is consistency, not keystrokes. An app-kit gives humans and agents one set of paved roads: typed design tokens, a component library, a loopback/app contract, a single data layer, and an MCP surface so agents discover the kit instead of reinventing it. The kit is what keeps a hundred agent-generated screens from looking like a hundred different apps.",
    },
    {
      id: "hexagonal-agentic-engineering",
      title: "Hexagonal architecture is a superpower in the age of agentic engineering",
      series: { name: "Building the Agentic Stack", part: 3, of: 4 },
      tags: ["architecture", "hexagonal", "agentic", "go"],
      date: "2026-06-08",
      read: "9 min",
      summary: "Ports-and-adapters gives agents a small, well-typed contract to code against and a domain core they can't accidentally couple to a database or a cloud. The same governed-agent core then runs locally over loopback and in AWS Lambda with nothing changed but the adapters — and every adapter boundary is a natural seam for replay tests and verification. Hexagonal design turns 'the agent rewrote half the app' into 'the agent swapped one adapter.'",
    },
    {
      id: "cue-for-agentic-engineering",
      title: "Why CUE is the right backbone for agentic engineering",
      series: { name: "Building the Agentic Stack", part: 4, of: 4 },
      tags: ["cue", "agentic", "configuration", "verification"],
      date: "2026-06-05",
      read: "12 min",
      summary: "Agents are far more reliable when they emit structured data than freeform prose. CUE gives you one typed schema that validates that data, unifies configuration, and compiles to JSON, YAML, or Go — so drift between what the schema says and what the agent produced becomes a build failure instead of a production incident. It is the single source of truth that makes agent output deterministic and defensible.",
    },
    {
      id: "agentic-verification",
      title: "Competing-incentive verification for agentic code factories",
      series: { name: "Level-4 Agentic Engineering", part: 3, of: 5 },
      tags: ["agentic", "verification", "governance"],
      date: "2026-03-18",
      read: "14 min",
      summary: "How to keep a patterned agentic layer honest: pit verifier agents with different incentives against the author agent, then source ground truth external to the source repo.",
    },
    {
      id: "mcp-skills-patterns",
      title: "MCP servers as engineering patterns, not just tools",
      series: { name: "Level-4 Agentic Engineering", part: 2, of: 5 },
      tags: ["mcp", "agentic", "architecture"],
      date: "2026-02-02",
      read: "9 min",
      summary: "Treat MCP capabilities like Kubernetes controllers — declare desired state, let the agent reconcile. Examples in Python with pydantic + CUE.",
    },
    {
      id: "finops-event-driven",
      title: "Event-driven FinOps: 70% cloud spend cut without touching reliability",
      tags: ["finops", "aws", "platform"],
      date: "2026-01-14",
      read: "11 min",
      summary: "Non-prod environments that spin up on first PR comment and tear down on idle. EventBridge rules, tag-driven right-sizing, and the dashboards that prove it.",
    },
    {
      id: "landing-zone-100",
      projectId: "landing-zone",
      title: "The 100-account AWS Landing Zone we run a bank on",
      tags: ["aws", "landing-zone", "ffiec", "pci-dss"],
      date: "2025-11-22",
      read: "16 min",
      summary: "Centralized networking with Transit Gateway, policy-as-code compliance gates, and the onboarding pattern that lets 30+ teams spin up new accounts in an afternoon.",
    },
    {
      id: "override-as-code",
      title: "Override-as-code: every security exception gets a Git commit",
      tags: ["security", "policy-as-code", "governance"],
      date: "2025-09-10",
      read: "7 min",
      summary: "Risk acceptance workflows that auditors love: exceptions carry peer-review, expiration, and automated re-checks. Sample OPA policies included.",
    },
    {
      id: "vpc-endpoint-hub",
      title: "Consolidating VPC endpoints: top-3 line item → negligible",
      tags: ["aws", "finops", "networking"],
      date: "2025-07-04",
      read: "8 min",
      summary: "Thousands of duplicate interface endpoints collapsed into one multi-AZ hub. Traffic analysis, the resolver setup, and the CloudWatch view that caught it.",
    },
    {
      id: "backstage-docs-as-code",
      title: "Cutting documentation drift 75% with Docs-as-Code + Backstage",
      series: { name: "Platform Foundations", part: 1, of: 3 },
      tags: ["backstage", "idp", "docs-as-code"],
      date: "2025-05-19",
      read: "10 min",
      summary: "Docs that ship with code, fail CI when stale, and render inline in Backstage. The pre-commit hooks and the review culture that make it stick.",
    },
    {
      id: "agentic-level4",
      title: "What Level-4 Agentic Software Engineering actually looks like",
      series: { name: "Level-4 Agentic Engineering", part: 1, of: 5 },
      tags: ["agentic", "ai", "strategy"],
      date: "2025-04-02",
      read: "12 min",
      summary: "One stage from full automation: architecture specs in, production-ready software and IaC out. The guardrails, the org change, the verification layer.",
    },
  ],

  /* ---------- Projects ---------- */
  projects: [
    {
      id: "agentic-code-factory",
      roleId: "paypal",
      owner: "org",
      title: "Agentic Code Factory",
      kind: "closed",
      org: "PayPal / First Citizens Bank",
      year: "2024 – present",
      tags: ["agentic", "mcp", "platform"],
      summary: "Independent patterned agentic layer that applies engineering patterns across projects — generates service catalogs, policy code, and IaC with controlled approval gates.",
      problem: "Developer throughput capped by specialization; security and compliance overhead grew linearly with team size.",
      impact: "3× throughput · consistent patterns · automated verification with competing incentives.",
      stack: ["Claude Code", "MCP", "CUE", "Python", "Terraform"],
    },
    {
      id: "landing-zone",
      roleId: "fcb",
      owner: "org",
      title: "100-Account AWS Landing Zone",
      kind: "pro",
      org: "First Citizens Bank",
      year: "2021 – 2025",
      tags: ["aws", "landing-zone", "ffiec", "pci-dss", "soc2"],
      summary: "Multi-account AWS architecture with Transit Gateway, centralized logging, and policy-as-code compliance gates. 30+ dev teams onboard in an afternoon.",
      problem: "Banking workloads required continuous FFIEC / PCI-DSS / SOC 2 compliance across 100+ AWS accounts with no dedicated account-per-team bottleneck.",
      impact: "100+ accounts · 30% YoY spend cut · audit trails zero-cost.",
      stack: ["AWS Organizations", "Transit Gateway", "Terraform", "OPA", "Sentinel"],
    },
    {
      id: "commandcenter-tools",
      roleId: "paypal",
      owner: "org",
      title: "PayPal Command Center Agentic Tooling",
      kind: "closed",
      org: "PayPal",
      year: "2025 – present",
      tags: ["sre", "agentic", "incident-management"],
      summary: "Agentic review gates, risk inventory, readiness drills, and scheduling for the PayPal SRE Command Center.",
      problem: "Command Center reliability readiness was manually audited; incident post-mortems produced reports but weak pattern libraries.",
      impact: "Real-time P0/P1 incident mitigation · artifact-driven PIR/RCA · agentically-scored GameDay readiness.",
      stack: ["Python", "Claude Code", "PagerDuty", "AWS"],
    },
    {
      id: "eks-blueprint",
      roleId: "fcb",
      owner: "org",
      title: "Bank-Hardened EKS Blueprint",
      kind: "pro",
      org: "First Citizens Bank",
      year: "2022 – 2025",
      tags: ["eks", "kubernetes", "cis", "gitops"],
      summary: "Multi-AZ, CIS-benchmark hardened EKS with OPA/Gatekeeper, Karpenter, and automated zero-day node patching.",
      problem: "Regulated workloads on Kubernetes with no tolerance for drift or zero-day exposure.",
      impact: "Zero-day patched within hours · <1% node cost overhead · mandatory-gate compliance.",
      stack: ["EKS", "Karpenter", "Argo CD", "OPA / Gatekeeper", "Kyverno"],
    },
    {
      id: "endpoint-hub",
      roleId: "fcb",
      owner: "org",
      title: "VPC Interface-Endpoint Hub",
      kind: "pro",
      org: "First Citizens Bank",
      year: "2023",
      tags: ["aws", "networking", "finops"],
      summary: "Replaced thousands of duplicate VPC interface endpoints with one multi-AZ endpoint hub via Route 53 resolver rules.",
      problem: "VPC endpoint costs were a top-3 AWS line item despite low utilization per endpoint.",
      impact: "Top-3 line item → negligible · hundreds of thousands saved annually.",
      stack: ["Transit Gateway", "Route 53 Resolver", "Terraform"],
    },
    {
      id: "agentic-kit",
      owner: "mine",
      title: "agentic-kit",
      kind: "closed",
      org: "Personal · in active development",
      year: "2026",
      tags: ["agentic", "go", "cuelang", "mcp", "governance"],
      summary: "A governed agentic platform in Go and CUE: a real Anthropic LLM client with a conformance suite, a governed agent loop (model turn → tool dispatch → governance screens), an MCP server kit, a fail-closed endpoint-guard (circuit breaker, strike ledger, proof-of-work, budget caps), and a hash-chained evidence/provenance store.",
      problem: "Raw LLM calls aren't a platform. Putting agents near production in a regulated enterprise needs budgets, injection defense, determinism, and provenance — by construction, not by hope.",
      impact: "Governed agent loop · record/replay determinism · cost-bounded endpoint guard · CUE-as-contract across the module.",
      stack: ["Go", "CUE", "Anthropic API", "MCP", "wazero"],
    },
    {
      id: "sextant",
      owner: "mine",
      title: "sextant",
      kind: "closed",
      org: "Personal · in active development",
      year: "2026",
      tags: ["code-intelligence", "go", "mcp", "developer-tools"],
      summary: "A multi-repo code-intelligence engine that extracts symbols and call edges into evidence records and answers concern-scoped queries — blast radius, callers/callees, cross-repo symbol search, staleness. Ships as a Go library, a CLI, and an MCP server that editors and AI agents query for code facts.",
      problem: "Coding agents waste tokens and make mistakes when they can't see how a large codebase actually fits together. They need fast, evidence-tiered answers, not a blind grep.",
      impact: "Multi-tool MCP surface · hash-gated incremental ingestion · native Go AST + tree-sitter via WASM · auto-refresh on HEAD drift.",
      stack: ["Go", "DuckDB", "tree-sitter (WASM)", "MCP", "CUE"],
    },
    {
      id: "app-kit",
      owner: "mine",
      title: "app-kit",
      kind: "closed",
      org: "Personal · early, active development",
      year: "2026",
      tags: ["platform", "go", "cuelang", "templ", "no-node"],
      summary: "A personal product platform that underpins my apps, with no Node in the build chain: a CUE-driven design-token pipeline (emits @theme CSS, DTCG JSON, and Go constants), a library of pure-Go SVG visualization components, and an MCP server that makes a licensed component library queryable by coding agents.",
      problem: "When agents generate most of the UI, consistency is the scarce resource. Humans and agents both need one set of paved roads — tokens, components, an app contract — or every screen drifts.",
      impact: "CUE → CSS/Go token pipeline · golden-tested SVG components · Tailwind v4 with no Node · MCP component catalog.",
      stack: ["Go", "CUE", "templ", "Tailwind v4", "SQLite", "MCP"],
    },
    {
      id: "cue-wasm",
      owner: "mine",
      title: "cue-wasm",
      kind: "oss",
      org: "Open Source · published to npm",
      year: "2026",
      tags: ["cuelang", "webassembly", "typescript", "react"],
      summary: "A WebAssembly wrapper around the official CUE Go API that brings CUE unification, validation, and export to the browser and Node. Uses phased loading — a lightweight reader WASM for instant interactivity, then warms the full evaluator in the background — and ships React hooks with Web Worker + IndexedDB support.",
      problem: "CUE has minimal first-party browser support, so building interactive CUE tooling on the web usually means a server round-trip.",
      impact: "Published npm package · phased reader/engine loading · React hooks · dockerized playground.",
      stack: ["Go (WASM)", "TypeScript", "React", "Web Workers"],
      github: "github.com/GeoffMillerAZ/cue-wasm",
    },
    {
      id: "pulumi-stateful-string",
      owner: "mine",
      title: "Pulumi Provider: Stateful String",
      kind: "oss",
      org: "Open Source",
      year: "2024",
      tags: ["pulumi", "go", "iac"],
      summary: "A Pulumi native provider for a string resource that stays stable across plan/apply and only changes when explicit trigger keys change — solving the 'stable-until-triggered' IaC problem that Pulumi's built-in Random resource doesn't, without forcing replacement of dependent resources.",
      problem: "Some configuration values (generated secrets, UUIDs) must stay constant until a specific rotation trigger changes — but standard resources replace on any config change.",
      impact: "Native provider with diff logic · multi-language SDKs (Go / TS / Python / C#) · reproducible devbox build.",
      stack: ["Go", "Pulumi Go Provider SDK", "devbox"],
      github: "github.com/GeoffMillerAZ/pulumi-provider-stateful-string",
    },
    {
      id: "geoffmiller-cloud",
      owner: "mine",
      title: "geoffmiller.cloud",
      kind: "closed",
      org: "Personal · in active development",
      year: "2026",
      tags: ["cuelang", "go", "agentic", "resume-as-data"],
      summary: "This system. A CUE-typed 'super résumé' that compiles into a public persona-lensed résumé site plus a private studio for honest, evidence-backed job-search tooling — built on my own Go/CUE/agentic platform, with a governed chat that answers only from the fact base.",
      problem: "Recruiters want one answer: does this candidate fit this JD? Make that trivial — and prove the agentic engineering by handing them a governed agent instead of claiming it.",
      impact: "Persona-lensed interactive résumé · CUE single source of truth · governed JD-chat (in progress) · public/private fact-base wall.",
      stack: ["Go", "CUE", "templ", "Datastar", "Anthropic", "AWS Lambda"],
    },
  ],

  /* ---------- Achievements ---------- */
  achievements: [
    {
      id: "agentic-incident-pipeline",
      projectId: "commandcenter-tools",
      title: "Artifact-driven incident & GameDay pipeline for the PayPal Command Center",
      metric: "P0/P1", metricUnit: "incident ops", year: "2025 – present",
      org: "PayPal", roleId: "paypal",
      tags: ["agentic", "sre", "incident-management"],
      summary: "Built a real-time P0/P1 incident-mitigation application and an agentic pipeline that models live incidents as structured data artifacts flowing through triage, mitigation, and PIR/RCA.",
      challenge: "Incident reviews produced one-shot documents; patterns repeated, lessons evaporated, and models re-solved the same problems each time.",
      approach: "Model incidents as structured artifacts moving deterministically through autonomous workflows; orchestrate investigation tracks, visualize timelines, and aggregate evidence in a Command Center app. GameDay tooling ingests incident logs and chat transcripts to generate agentically-scored readiness feedback.",
      outcome: "Faster live incident recovery, reusable mitigation patterns instead of throwaway reports, and individualized GameDay readiness scoring across business units.",
      whyItMatters: "Turns operational pain into compounding institutional knowledge — the team gets faster after every outage instead of slower.",
      stack: ["Claude Code", "Go", "CUE", "PagerDuty", "AWS"],
    },
    {
      id: "landing-zone-100",
      projectId: "landing-zone",
      title: "AWS landing zone for 100+ regulated accounts",
      metric: "100+", metricUnit: "accounts", year: "2021 – 2025",
      org: "First Citizens Bank", roleId: "fcb",
      tags: ["aws", "landing-zone", "ffiec", "pci-dss", "soc2"],
      summary: "Multi-account architecture with Transit Gateway, centralized logging, and policy-as-code compliance gates — onboarding 30+ teams in an afternoon.",
      challenge: "Banking workloads required continuous FFIEC / PCI-DSS / SOC 2 compliance with no per-team Ops bottleneck. Account sprawl was already a budget threat.",
      approach: "AWS Organizations + Control Tower with Terraform-driven account vending, OPA/Sentinel guardrails as merge-gate, hub-and-spoke Transit Gateway, and centralized log aggregation. Compliance isn't a phase — it's the default branch.",
      outcome: "100+ accounts governed. New teams onboard in an afternoon. Audit trails generated for free as a byproduct of the platform.",
      whyItMatters: "Made compliance the cheap path. The number that scales linearly with team count is a Terraform PR, not a Ticket-of-Doom.",
      stack: ["AWS Organizations", "Control Tower", "Transit Gateway", "Terraform", "OPA", "Sentinel"],
    },
    {
      id: "finops-30",
      projectId: "endpoint-hub",
      title: "30% YoY AWS spend reduction at a regulated bank",
      metric: "30%", metricUnit: "YoY cut", year: "2022 – 2024",
      org: "First Citizens Bank", roleId: "fcb",
      tags: ["finops", "aws", "platform"],
      summary: "Event-driven FinOps automation that trims waste continuously without touching reliability — including the VPC endpoint hub that killed a top-3 line item.",
      challenge: "AWS spend was growing faster than the workload. Reservation coverage drifted. VPC interface endpoints duplicated thousands of times. No single owner.",
      approach: "Continuous savings-plan optimizer, idle-resource janitor, anomaly alerts wired into Slack, and a Route 53 resolver-based shared endpoint hub that collapsed redundancy. All in IaC, all gated by policy.",
      outcome: "30% YoY reduction. Endpoint hub alone deleted hundreds of thousands of dollars from the bill. Reliability metrics unchanged.",
      whyItMatters: "Proves regulated FinTech can be both compliant and cost-disciplined — the two are usually framed as a tradeoff.",
      stack: ["AWS", "Terraform", "Lambda", "Athena", "Slack"],
    },
    {
      id: "team-1-to-18",
      title: "Built infra org from 1 to 18 — and a 12-person platform team",
      metric: "1 → 18", metricUnit: "engineers", year: "2018 – 2025",
      org: "REPAY · First Citizens Bank", roleId: "repay",
      tags: ["leadership", "platform", "team-building"],
      summary: "Two team-building cycles back-to-back: REPAY infra 1→18, then a 12-person platform team at FCB built from scratch.",
      challenge: "Both orgs needed to scale infra and platform engineering without it becoming an Ops bottleneck — or a hiring bonfire.",
      approach: "Hire for systems-thinking and writing ability, not tool-of-the-week. Run a Community-of-Practice model so platform consumers self-serve. Document patterns until the team is no longer the bottleneck.",
      outcome: "REPAY: 1 → 18 across infra and SRE. FCB: 12-person platform team supporting 30+ product teams across 100+ accounts. Both orgs running on patterns, not heroics.",
      whyItMatters: "The hardest part of platform engineering isn't the platform — it's the org around it. Got to run that play twice.",
      stack: ["Hiring", "CoP model", "Mentorship", "Docs-as-code"],
    },
    {
      id: "pci-greenfield",
      title: "PCI-DSS first-pass green on a green-field stack",
      metric: "0", metricUnit: "criticals", year: "2019",
      org: "REPAY", roleId: "repay",
      tags: ["pci-dss", "security", "platform"],
      summary: "Designed a payments-processing AWS architecture that passed its first PCI-DSS audit with zero criticals.",
      challenge: "Build a regulated payments platform that auditors couldn't poke holes in, on a deadline, with a small team.",
      approach: "Network segmentation by control scope, KMS-everywhere, minimal-IAM with break-glass auditing, and IaC that made every control reviewable as a PR diff. Audit prep was exporting the repo.",
      outcome: "First-pass PCI-DSS audit closed with zero criticals. Subsequent audits ran in days, not months.",
      whyItMatters: "Demonstrates the discipline behind 'compliance as code' — when the audit is the side effect of how you build, it stops being a project.",
      stack: ["AWS", "Terraform", "KMS", "VPC", "Cloudtrail"],
    },
    {
      id: "eks-zeroday",
      projectId: "eks-blueprint",
      title: "Bank-hardened EKS — zero-days patched in hours",
      metric: "<4h", metricUnit: "to patch", year: "2022 – 2025",
      org: "First Citizens Bank", roleId: "fcb",
      tags: ["kubernetes", "eks", "security", "cis"],
      summary: "EKS blueprint with CIS-benchmark hardening, OPA/Gatekeeper, Karpenter, and automated zero-day node patching that runs in hours.",
      challenge: "Regulated workloads on Kubernetes, with zero tolerance for drift, vulnerable nodes, or weekend-long patching windows.",
      approach: "Karpenter-driven node lifecycle so patching = re-provisioning, OPA/Gatekeeper + Kyverno as merge-gate, Argo CD for declarative app delivery, immutable AMIs published continuously.",
      outcome: "Zero-days patched in under 4 hours from CVE publication, fleet-wide. Less than 1% node-cost overhead from the safety machinery.",
      whyItMatters: "Lets a bank run modern Kubernetes without trading reliability for speed — the patch story alone makes the platform defensible to security review.",
      stack: ["EKS", "Karpenter", "Argo CD", "OPA / Gatekeeper", "Kyverno"],
    },
    {
      id: "onboarding-months-to-day",
      title: "Cloud onboarding: months → a single day",
      metric: "months → 1d", metricUnit: "lead time", year: "2017 – 2021",
      org: "REPAY", roleId: "repay",
      tags: ["aws", "iac", "platform"],
      summary: "Built reusable landing-zone and platform patterns so teams could onboard new applications, consume shared services, and integrate secure networking in a day instead of months.",
      challenge: "Every new application onboarding was hand-rolled. Teams couldn't afford a multi-month setup per workload while still meeting PCI and security requirements.",
      approach: "Reusable Terraform patterns for account vending, shared services, edge networking, and security baselines — every new onboarding started from the previous one, never from scratch, with guardrails enforced as policy.",
      outcome: "Application onboarding lead time collapsed from months to a single day for pattern-fitting workloads, while staying inside the secure landing zone.",
      whyItMatters: "Infrastructure is a compounding asset — every onboarding should make the next one cheaper, not just done.",
      stack: ["AWS", "Terraform", "Kubernetes", "Backstage"],
    },
  ],

  /* ---------- Resources ---------- */
  resources: [
    // YouTube
    { kind: "youtube",  title: "Fireship",                 by: "Jeff Delaney",      note: "100-second explainers that get technical quickly." },
    { kind: "youtube",  title: "ThePrimeagen",             by: "Michael Paulson",   note: "Fast code, strong opinions, terminal-first workflows." },
    { kind: "youtube",  title: "Jim Kwik",                 by: "Jim Kwik",          note: "Learning how to learn — foundational for picking up new stacks fast." },
    { kind: "youtube",  title: "HashiCorp",                by: "HashiCorp",         note: "Deep dives on Terraform, Vault, and Consul." },
    // Podcasts
    { kind: "podcast",  title: "Kubernetes Podcast",       by: "Google",            note: "Release breakdowns and community interviews." },
    { kind: "podcast",  title: "Software Engineering Daily", by: "SED",             note: "Long-form engineering conversations — breadth across the field." },
    { kind: "podcast",  title: "Latent Space",             by: "swyx & Alessio",    note: "Applied AI engineering, agentic patterns, and MCP deep-dives." },
    { kind: "podcast",  title: "The Changelog",            by: "Jerod & Adam",      note: "Open source under the hood." },
    // Books
    { kind: "book",     title: "Accelerate",               by: "Forsgren, Humble, Kim", note: "The DORA metrics bible — what actually predicts software delivery performance." },
    { kind: "book",     title: "Team Topologies",          by: "Skelton & Pais",    note: "Conway's Law turned into a team-design playbook." },
    { kind: "book",     title: "Staff Engineer",           by: "Will Larson",       note: "What the IC track looks like above senior." },
    { kind: "book",     title: "The Phoenix Project",      by: "Gene Kim et al.",   note: "DevOps origin story, still the clearest intro." },
    { kind: "book",     title: "An Elegant Puzzle",        by: "Will Larson",       note: "Engineering management as systems design." },
    // Blogs
    { kind: "blog",     title: "lethain.com",              by: "Will Larson",       note: "Weekly essays on engineering leadership." },
    { kind: "blog",     title: "Simon Willison",           by: "simonwillison.net", note: "Daily LLM experimentation — practical, cited, reproducible." },
    { kind: "blog",     title: "Charity Majors",           by: "charity.wtf",       note: "Observability philosophy, hiring, and SRE culture." },
    { kind: "blog",     title: "Last Week in AWS",         by: "Corey Quinn",       note: "FinOps-adjacent AWS news with bite." },
    { kind: "blog",     title: "Anthropic Engineering",    by: "Anthropic",         note: "Applied agent and MCP engineering writeups." },
  ],

  /* ---------- About Me ---------- */
  about: [
    { id: "family",    title: "Dad mode",         body: "Two kids. Most of my weekend build-time is a kid on one knee pointing at which wire goes where.", icon: "users" },
    { id: "bjj",       title: "Brazilian Jiu-Jitsu", body: "White belt energy, permanent. BJJ is the best debugging practice I know — you think your position is great until someone shows you why it isn't.", icon: "shield" },
    { id: "latin",     title: "Latin dancing",    body: "Salsa, Bachata, Merengue, Cha-Cha. It keeps me fluent in a thing that's not keyboard-shaped.", icon: "music" },
    { id: "rc",        title: "RC drones + monster trucks", body: "Anything with a brushless motor and a receiver. I like the tuning loop — telemetry, tweak, fly again. Same loop, smaller stakes.", icon: "drone" },
    { id: "ai",        title: "Tinkering with AI", body: "Nights and weekends: building agentic harnesses, poking MCP servers, wiring small models into weirder workflows. This site is part of that.", icon: "sparkles" },
    { id: "build",     title: "Workshop",         body: "I build and fix things with the kids. No great woodworker, but a lot of time on 'why did that break' conversations — which is most of engineering.", icon: "tool" },
  ],
};
