// Code generated by tools/jsxbuild from EntityCards.jsx. DO NOT EDIT.
const ENTITY_KIND = {
  project: { label: "Project", icon: "folder", tone: "var(--neon-pink)" },
  role: { label: "Experience", icon: "file", tone: "var(--neon-cyan)" },
  article: { label: "Writing", icon: "book", tone: "var(--neon-amber)" },
  edu: { label: "Education", icon: "award", tone: "var(--neon-purple)" },
  cert: { label: "Certification", icon: "award", tone: "var(--neon-blue)" },
  // `compass` is the closest glyph Icon.jsx carries — there is no radar or
  // target mark, and inventing one for a chat card is not worth an SVG.
  blip: { label: "Radar", icon: "compass", tone: "var(--neon-purple)" }
};
const STOP = new Set("the a an and or of for to in on with at from is are was were how what why does did do he his him geoff tell me about you your this that it".split(" "));
const terms = (s) => {
  var _a;
  return ((_a = String(s || "").toLowerCase().match(/[a-z0-9+#.]{2,}/g)) == null ? void 0 : _a.filter((t) => !STOP.has(t))) || [];
};
const hits = (qSet, terms2) => {
  let n = 0;
  terms2.forEach((t) => {
    if (qSet.has(t)) n++;
  });
  return n;
};
const buildEntityIndex = () => {
  const D = window.SITE_DATA || {};
  const out = [];
  (D.projects || []).forEach((p) => out.push({
    kind: "project",
    id: p.id,
    title: p.title,
    line: p.summary,
    meta: [p.org, p.year].filter(Boolean).join(" \xB7 "),
    chips: (p.stack || []).slice(0, 5),
    titleTerms: terms(p.title),
    bodyTerms: terms([p.summary, p.problem, p.impact, (p.stack || []).join(" "), (p.tags || []).join(" ")].join(" ")),
    go: () => {
      var _a;
      return (_a = window.GO) == null ? void 0 : _a.call(window, "projects", { projectId: p.id });
    }
  }));
  (D.roles || []).forEach((r) => out.push({
    kind: "role",
    id: r.id,
    title: r.company,
    line: r.tagline,
    meta: [r.title, r.start + " \u2014 " + r.end].filter(Boolean).join(" \xB7 "),
    chips: (r.scope || []).slice(0, 4),
    titleTerms: terms(r.company),
    bodyTerms: terms([r.title, r.tagline, (r.scope || []).join(" "), (r.bullets || []).map((b) => b.text).join(" ")].join(" ")),
    go: () => {
      var _a;
      return (_a = window.GO) == null ? void 0 : _a.call(window, "resume", { roleId: r.id });
    }
  }));
  (D.articles || []).forEach((a) => out.push({
    kind: "article",
    id: a.id,
    title: a.title,
    line: a.dek || a.summary,
    meta: a.date ? new Date(a.date).toLocaleDateString("en-US", { month: "short", year: "numeric" }) : "",
    chips: (a.tags || []).slice(0, 4),
    titleTerms: terms(a.title),
    bodyTerms: terms([a.dek, a.summary, (a.tags || []).join(" ")].join(" ")),
    go: () => {
      var _a;
      return (_a = window.GO) == null ? void 0 : _a.call(window, "articles", { articleId: a.id });
    }
  }));
  (D.education || []).forEach((e, i) => out.push({
    kind: "edu",
    id: "edu-" + i,
    title: e.degree,
    line: e.honors || "",
    meta: [e.school, e.year].filter(Boolean).join(" \xB7 "),
    chips: [],
    titleTerms: terms(e.degree),
    bodyTerms: terms([e.honors, e.school].join(" ")),
    go: () => {
      var _a;
      return (_a = window.GO) == null ? void 0 : _a.call(window, "resume");
    }
  }));
  (D.certifications || []).forEach((c, i) => out.push({
    kind: "cert",
    id: "cert-" + i,
    title: c.name,
    line: c.summary || "",
    meta: [c.issuer, c.year].filter(Boolean).join(" \xB7 "),
    chips: (c.tags || []).slice(0, 3),
    titleTerms: terms(c.name),
    bodyTerms: terms([c.summary, c.issuer, (c.tags || []).join(" ")].join(" ")),
    go: () => {
      var _a;
      return (_a = window.GO) == null ? void 0 : _a.call(window, "resume");
    }
  }));
  return out;
};
const buildBlipIndex = () => {
  const R = window.RADAR;
  if (!R || !window.featureOn || !window.featureOn("radar")) return [];
  return R.blips.concat(R.watch || []).map((b) => ({
    kind: "blip",
    id: b.id,
    title: b.name,
    line: b.verdictLine,
    meta: [
      b.ring ? b.ring.toUpperCase() : "WATCHING",
      b.basis,
      b.movedCount > 0 ? "changed my mind" : null
    ].filter(Boolean).join(" \xB7 "),
    chips: (b.context || []).slice(0, 3),
    titleTerms: terms(b.name),
    // Each alias is its own term-set, not a bag mixed into the title. "Argo CD"
    // and "ArgoCD" are two ways to name one thing and either should match
    // completely; flattening them into one list would make a query naming one of
    // them look like a half-match on a longer name.
    aliasTermSets: (b.aliases || []).map((a) => terms(a)).filter((t) => t.length),
    bodyTerms: terms([b.verdictLine, b.why, b.scope, b.category].join(" ")),
    go: () => {
      var _a;
      return (_a = window.GO) == null ? void 0 : _a.call(window, "radar", { blipId: b.id });
    }
  }));
};
let ENTITY_INDEX = null;
let BLIP_INDEX = null;
let TITLE_DF = null;
const buildTitleDF = (index) => {
  const df = /* @__PURE__ */ new Map();
  index.forEach((e) => {
    new Set(e.titleTerms).forEach((t) => df.set(t, (df.get(t) || 0) + 1));
  });
  return df;
};
const entitiesFor = (question, opts) => {
  const o = opts || {};
  const limit = o.limit || 3;
  const exclude = new Set(o.exclude || []);
  if (!ENTITY_INDEX) {
    ENTITY_INDEX = buildEntityIndex();
    TITLE_DF = buildTitleDF(ENTITY_INDEX);
  }
  if (!BLIP_INDEX) {
    BLIP_INDEX = buildBlipIndex();
  }
  const qSet = new Set(terms(question));
  if (!qSet.size) return [];
  const scored = ENTITY_INDEX.filter((e) => !exclude.has(e.kind + ":" + e.id)).map((e) => {
    const tHits = hits(qSet, e.titleTerms);
    const bHits = hits(qSet, e.bodyTerms);
    const unique = e.titleTerms.some((t) => qSet.has(t) && TITLE_DF.get(t) === 1);
    if (tHits < 2 && !unique) return null;
    return {
      e,
      // Body hits only break ties between things the question named; they
      // can never promote something it did not.
      // A unique-term hit is a direct nomination and should outrank a
      // partial match on a longer title.
      score: (unique ? 1 : tHits / Math.max(1, e.titleTerms.length)) + Math.min(bHits, 6) * 0.02
    };
  }).filter(Boolean).sort((a, b) => b.score - a.score);
  const picked = scored.slice(0, limit).map((x) => x.e);
  const blip = blipEntities(question, { exclude: o.exclude })[0];
  if (blip && picked.length < limit + 1) picked.push(blip);
  return picked.slice(0, limit + (blip ? 1 : 0));
};
const blipEntities = (question, opts) => {
  const o = opts || {};
  const exclude = new Set(o.exclude || []);
  if (!BLIP_INDEX) {
    BLIP_INDEX = buildBlipIndex();
  }
  if (!BLIP_INDEX.length) return [];
  const df = /* @__PURE__ */ new Map();
  BLIP_INDEX.forEach((e) => {
    const all = new Set(e.titleTerms.concat(...e.aliasTermSets));
    all.forEach((t) => df.set(t, (df.get(t) || 0) + 1));
  });
  const qSet = new Set(terms(question));
  if (!qSet.size) return [];
  const coverage = (qs, termList) => {
    if (!termList.length) return 0;
    let n = 0;
    new Set(termList).forEach((t) => {
      if (qs.has(t)) n++;
    });
    return n / new Set(termList).size;
  };
  const scored = BLIP_INDEX.filter((e) => !exclude.has(e.kind + ":" + e.id)).map((e) => {
    let best = coverage(qSet, e.titleTerms);
    e.aliasTermSets.forEach((a) => {
      best = Math.max(best, coverage(qSet, a));
    });
    const tHits = hits(qSet, e.titleTerms);
    const unique = e.titleTerms.concat(...e.aliasTermSets).some((t) => t.length >= 4 && qSet.has(t) && df.get(t) === 1);
    if (best < 1 && !unique && !(tHits >= 2 && best >= 0.5)) return null;
    const bHits = hits(qSet, e.bodyTerms);
    return { e, score: best + Math.min(bHits, 6) * 0.01 };
  }).filter(Boolean).sort((a, b) => b.score - a.score);
  return scored.slice(0, 1).map((x) => x.e);
};
const EntityCard = ({ entity }) => {
  const k = ENTITY_KIND[entity.kind] || ENTITY_KIND.project;
  return /* @__PURE__ */ React.createElement("button", { type: "button", className: "entc", style: { "--entc-tone": k.tone }, onClick: entity.go }, /* @__PURE__ */ React.createElement("span", { className: "entc-kicker" }, /* @__PURE__ */ React.createElement(Icon, { name: k.icon, size: 11 }), k.label), /* @__PURE__ */ React.createElement("span", { className: "entc-title" }, entity.title), entity.meta && /* @__PURE__ */ React.createElement("span", { className: "entc-meta" }, entity.meta), entity.line && /* @__PURE__ */ React.createElement("span", { className: "entc-line" }, entity.line), entity.chips.length > 0 && /* @__PURE__ */ React.createElement("span", { className: "entc-chips" }, entity.chips.map((c) => /* @__PURE__ */ React.createElement("span", { key: c, className: "entc-chip" }, c))), /* @__PURE__ */ React.createElement("span", { className: "entc-go" }, "Open", /* @__PURE__ */ React.createElement(Icon, { name: "chevronRight", size: 11 })));
};
const EntityCards = ({ entities }) => {
  if (!entities || !entities.length) return null;
  return /* @__PURE__ */ React.createElement("div", { className: "entc-grid" }, entities.map((e) => /* @__PURE__ */ React.createElement(EntityCard, { key: e.kind + ":" + e.id, entity: e })));
};
window.entitiesFor = entitiesFor;
window.blipEntities = blipEntities;
window.EntityCard = EntityCard;
window.EntityCards = EntityCards;
