// Code generated by tools/jsxbuild from SpecAgentic.jsx. DO NOT EDIT.
(function() {
  const SpecPageShell = window.SpecPageShell;
  const SpecSection = window.SpecSection;
  const SpecSignature = window.SpecSignature;
  const AgenticGradient = window.AgenticGradient;
  const CSS = `
.specag-legend {
  list-style: none; margin: 16px 0 0; padding: 14px 16px 12px;
  background: var(--bg); border: 1px solid var(--line-soft); border-radius: var(--rad-sm);
  display: flex; flex-direction: column; gap: 9px;
}
/* --text-src, not --text-mute. MEASURED: --text-mute on --bg (the panel this
   legend actually sits on) is 3.42:1 dark and 3.08:1 terminal, and this is 12.5px
   text that a reader has to read to understand the picture above it. --text-src
   exists in this repo for exactly that case, is declared in all four palettes and
   is gated by "task spa:contrast" at >= 4.5:1. Same change was made in
   SpecAgenticGradient.jsx so the two legends on this page agree. */
.specag-legend li {
  display: grid; grid-template-columns: 18px 1fr; gap: 10px; align-items: start;
  font-size: 12.5px; line-height: 1.6; color: var(--text-src); max-width: 92ch;
}
.specag-legend b { color: var(--text); font-weight: 600; }
.specag-sw {
  width: 14px; height: 14px; margin-top: 3px; border-radius: 3px;
  background: var(--specag-sw, var(--accent));
  box-shadow: 0 0 10px -2px var(--specag-sw, var(--accent));
}
.specag-sw.is-dashed {
  background: transparent;
  border: 1px dashed var(--spec-tone, var(--accent));
  box-shadow: none;
}

.specag-try {
  margin-top: 18px; padding: 16px 18px 14px;
  display: flex; flex-wrap: wrap; align-items: center; gap: 14px;
  background: color-mix(in oklab, var(--neon-cyan) 6%, var(--bg-1));
  border: 1px solid color-mix(in oklab, var(--neon-cyan) 32%, var(--line));
  border-left: 2px solid var(--neon-cyan);
  border-radius: var(--rad);
}
.specag-try-body { flex: 1 1 380px; min-width: 0; }
.specag-try-kicker {
  display: block; margin-bottom: 6px;
  font-family: var(--font-mono); font-size: 10px; letter-spacing: 0.1em;
  text-transform: uppercase; color: var(--neon-cyan);
}
.specag-try-text { margin: 0; max-width: 74ch; font-size: 13.5px; line-height: 1.65; color: var(--text-dim); }
.specag-try-cta { background: var(--neon-cyan); border-color: var(--neon-cyan); color: #1a1423; flex: 0 0 auto; }

.specag-ledger { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 10px; }
.specag-row {
  padding: 15px 17px 14px;
  background: var(--bg-1); border: 1px solid var(--line);
  border-left: 2px solid var(--line); border-radius: var(--rad-sm);
}
.specag-row.is-enforced   { border-left-color: var(--neon-cyan); }
.specag-row.is-render     { border-left-color: color-mix(in oklab, var(--neon-cyan) 45%, var(--line)); }
.specag-row.is-convention { border-left-style: dashed; border-left-color: var(--text-faint); }
.specag-row-head { display: flex; flex-wrap: wrap; align-items: baseline; gap: 10px; margin-bottom: 9px; }
.specag-n {
  font-family: var(--font-mono); font-size: 10px; letter-spacing: 0.1em;
  color: var(--text-faint); flex: 0 0 auto;
}
.specag-claim { flex: 1 1 300px; min-width: 0; font-size: 14.5px; line-height: 1.45; font-weight: 600; color: var(--text); }
.specag-row-head .spec-chip { flex: 0 0 auto; cursor: default; }
.specag-how { margin: 0; max-width: 84ch; font-size: 13px; line-height: 1.65; color: var(--text-dim); }
.specag-where {
  margin: 10px 0 0; padding-top: 9px; border-top: 1px solid var(--line-soft);
  font-family: var(--font-mono); font-size: 10.5px; line-height: 1.7; color: var(--text-faint);
}
.specag-where code { font-family: inherit; color: var(--text-mute); }
.specag-src {
  margin: 14px 0 0; padding-top: 11px; border-top: 1px solid var(--line-soft);
  font-family: var(--font-mono); font-size: 10.5px; line-height: 1.6; color: var(--text-faint);
  max-width: 92ch;
}
.specag-note { max-width: 76ch; font-size: 13.5px; line-height: 1.75; color: var(--text-dim); }
.specag-note + .specag-note { margin-top: 12px; }

/* \u2500\u2500 added 2026-08-08 with the restructure \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */

/* The lit token, and its light-theme correction, declared once for every element
   below that paints with it. Same :not() chain and same measured 58% as
   SpecAgenticGradient.jsx \u2014 see that file's header for why the chain is
   load-bearing and what the raw token measures without it. */
.specag-force, .specag-tier, .specag-link, .specag-prose { --specag-lit: var(--neon-cyan); }
:root[data-theme="light"]:not([data-aesthetic="terminal"]):not([data-aesthetic="outrun"]) .specag-force,
:root[data-theme="light"]:not([data-aesthetic="terminal"]):not([data-aesthetic="outrun"]) .specag-tier,
:root[data-theme="light"]:not([data-aesthetic="terminal"]):not([data-aesthetic="outrun"]) .specag-link,
:root[data-theme="light"]:not([data-aesthetic="terminal"]):not([data-aesthetic="outrun"]) .specag-prose {
  --specag-lit: color-mix(in oklab, var(--neon-cyan) 58%, #000);
}

.specag-prose { max-width: 84ch; font-size: 13.5px; line-height: 1.75; color: var(--text-dim); }
.specag-prose + .specag-prose { margin-top: 13px; }
.specag-prose strong, .specag-note strong { color: var(--text); font-weight: 600; }
/* --text-src, not --text-mute: these are file paths and identifiers inside
   running prose, so they are read, not skimmed. MEASURED on --text-mute: 3.73
   dark and 3.19 terminal, both under AA. */
.specag-prose code, .specag-note code { font-family: var(--font-mono); font-size: 0.9em; color: var(--text-src); }

.specag-h {
  margin: 26px 0 0; display: flex; flex-wrap: wrap; align-items: baseline; gap: 10px;
  font-size: 14.5px; font-weight: 600; color: var(--text);
}
.specag-h:first-child { margin-top: 0; }
.specag-h + .specag-prose { margin-top: 9px; }

/* The provenance tier tag. Three values, used verbatim across four sections and
   both visuals \u2014 see the header. Small mono text, so --text-src (>= 4.5:1 in all
   four palettes) rather than --text-mute (3.08:1 on terminal). */
.specag-tier {
  display: inline-block; padding: 2px 7px; vertical-align: baseline;
  font-family: var(--font-mono); font-size: 9px; letter-spacing: 0.1em;
  text-transform: uppercase; color: var(--text-src); white-space: nowrap;
  border: 1px solid var(--line); border-radius: 999px;
}
.specag-tier.is-here {
  color: var(--specag-lit);
  border-color: color-mix(in oklab, var(--specag-lit) 55%, var(--line));
}

/* The force ranking. A TEXT LADDER WITH CHIPS, NOT A DIAGRAM \u2014 deliberately, and
   the reason is in the file header: the gate mechanism is drawn once, on the
   agentic-harness project record, and drawing it again here would be the second
   drawing of one mechanism. */
.specag-force { list-style: none; margin: 14px 0 0; padding: 0; display: flex; flex-direction: column; gap: 8px; }
.specag-force li {
  padding: 12px 15px 11px;
  background: var(--bg-1); border: 1px solid var(--line);
  border-left: 2px solid var(--specag-force-tone, var(--line));
  border-radius: var(--rad-sm);
}
.specag-force-head { display: flex; flex-wrap: wrap; align-items: baseline; gap: 10px; margin-bottom: 6px; }
.specag-force-n {
  flex: 0 0 auto; font-family: var(--font-mono); font-size: 10px; letter-spacing: 0.1em; color: var(--text-src);
}
.specag-force-t { flex: 1 1 220px; min-width: 0; font-size: 13.5px; font-weight: 600; color: var(--text); }
.specag-force-what { margin: 0; max-width: 84ch; font-size: 12.5px; line-height: 1.65; color: var(--text-dim); }
.specag-force-cost {
  margin: 6px 0 0; max-width: 84ch;
  font-family: var(--font-mono); font-size: 10.5px; line-height: 1.65; color: var(--text-src);
}

/* Inline cross-link. Same idiom as .specgv-link / .specfin-link so the three
   pages' outbound links are one thing a reader learns once. */
.specag-link {
  appearance: none; border: 0; padding: 0; background: none; cursor: pointer;
  font: inherit; color: var(--text);
  border-bottom: 1px solid var(--spec-tone, var(--accent));
}
.specag-link:focus-visible { outline: 2px solid var(--spec-tone, var(--accent)); outline-offset: 2px; }

@media (max-width: 640px) {
  /* flex-basis is a HEIGHT once the container turns into a column, so the
     380px basis that keeps the copy and the button side by side on a wide
     screen becomes 380px of dead space on a narrow one. */
  .specag-try { flex-direction: column; align-items: stretch; }
  .specag-try-body { flex: 0 0 auto; }
  .specag-try-cta { width: 100%; justify-content: center; }
  .specag-row-head { gap: 7px; }
}

/* Light theme. --neon-cyan and --accent are both remapped for light in
   styles.css, so the tones survive; the one thing that does not is the swatch
   glow, which reads as a smudge on white.

   GATED 2026-08-08, and the gate matters even though these two rules are
   cosmetic. styles.css declares [data-aesthetic="terminal"] and
   [data-aesthetic="outrun"] AFTER [data-theme="light"] at equal specificity and
   remaps the surfaces back to a DARK palette, so an ungated [data-theme="light"]
   rule fires on a dark panel \u2014 which is how the CTA's label was being forced to
   #ffffff on a light-cyan button under light+terminal, and how the swatch glow
   was being stripped on the two aesthetics that need it most. Left ungated, this
   pair is also the pattern the next author copies. */
:root[data-theme="light"]:not([data-aesthetic="terminal"]):not([data-aesthetic="outrun"]) .specag-sw { box-shadow: none; }
:root[data-theme="light"]:not([data-aesthetic="terminal"]):not([data-aesthetic="outrun"]) .specag-try-cta { color: #ffffff; }
`;
  const Tip = ({ x, y, dir, color }) => {
    const d = dir === "left" ? "M" + x + " " + y + " l7 -4.5 l0 9 z" : dir === "down" ? "M" + x + " " + y + " l-4.5 -7 l9 0 z" : dir === "up" ? "M" + x + " " + y + " l-4.5 7 l9 0 z" : "M" + x + " " + y + " l-7 -4.5 l0 9 z";
    return /* @__PURE__ */ React.createElement("path", { d, fill: color, pointerEvents: "none" });
  };
  const CY = "var(--neon-cyan)";
  const PK = "var(--spec-tone, var(--accent))";
  const NE = "var(--text-dim)";
  const SIG_NOTES = {
    q: {
      title: "Your question is the retrieval key",
      body: "The function that picks a quote is keyed on what you typed. It is never keyed on what the model replied, because it never sees what the model replied.",
      detail: "ChatPage.jsx passes the raw question string to window.recommendationsFor. The model's response object touches that path once, and only to switch it off."
    },
    agent: {
      title: "The model, server-side",
      body: "A governed agent behind an HTTP endpoint. It writes prose. Writing prose is the entirety of its job on this page.",
      detail: "It is not asked which recommendation to show, and it is not shown the recommendations. There is no tool it can call that returns a person's name attached to a sentence."
    },
    prose: {
      title: "Model-authored text, fenced into one region",
      body: "Everything the model writes is rendered inside the answer body, under the label geoff-agent. Nothing it writes is rendered as someone else's words.",
      detail: "The fence is not a rule about tone. It is that the component which renders quoted text takes its text from a different variable, populated by a different function, from a different source."
    },
    off: {
      title: "The one edge, and it is an off switch",
      body: "If the governed agent marks a response as blocked, the quote list is emptied. That is the whole of the model's influence over what gets quoted.",
      detail: "A testimonial rendered underneath a refusal is noise, so the suppression is deliberate. Note the direction of the asymmetry: the model can take a real quote away, and has no mechanism by which to add any text at all."
    },
    pick: {
      title: "recommendationsFor(), running in this browser",
      body: "A pure scoring function over records already in the page. Theme overlap, corroborated claim, evidential strength, recency, and the vantage the letter was written from \u2014 then at most two results.",
      detail: "No network call and no generation. The worst thing this function can do is return a less relevant real quote, or return nothing, which is what it does when the question matches no theme."
    },
    span: {
      title: "What it returns is stored text",
      body: "Not a summary and not a paraphrase \u2014 a span that was selected out of the letter and stored next to it.",
      detail: "The renderer prints hit.quote.text, and its only source of text is window.SITE_DATA. There is no value it could print that a real person did not write."
    },
    screen: {
      title: "One answer card, two independent sources",
      body: "What you read is composed of two regions that were produced by different machinery: prose the model wrote, and quoted text it never touched.",
      detail: "That composition is the claim, and a reader can hold the site to it, because the boundary is a property of the code rather than of a system prompt."
    },
    cue: {
      title: "The fact base",
      body: "Nineteen recommendations, modelled in CUE, with the text exactly as each person wrote it. Nothing in the repository is permitted to edit that text.",
      detail: "The schema keeps themes, corroborated claim ids, evidential strength and the relationship it was written from \u2014 so retrieval can rank without anyone hand-picking a favourite."
    },
    gate: {
      title: "The substring check \u2014 and exactly how far it goes",
      body: "Every pull quote must be an exact substring of the verbatim letter, checked twice: once by the build, once again in this browser before anything is drawn.",
      detail: "gates.CheckRecommendationQuotes compares byte-for-byte with no normalisation \u2014 the only two mismatches this rule has caught were a straight apostrophe standing in for a curly one, and folding those would pass exactly the failure it exists to find. resumecheck runs it as check 8 of 8 and the deploy runs resumecheck before it publishes. Specializations.jsx then re-runs the same test at render, which is the copy a reader can verify without trusting the build. Note what is NOT load-bearing here: the property this page is really about is the missing wire above. Even with no gate at all, the model never authors attributed text."
    },
    bundle: {
      title: "Stored records, shipped with the page",
      body: "The records are in the bundle the browser already downloaded. That is what makes the retrieval above a local function call instead of a request to something you would have to trust.",
      detail: "It is also why the claim is checkable rather than merely stated: view-source is the audit."
    }
  };
  const AgenticSignature = () => /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(
    DiagramExplorer,
    {
      viewBox: "0 0 760 442",
      notes: SIG_NOTES,
      ariaLabel: "This is the third of three cases set out at the top of this page: the one where the process could not be fixed in advance, so the output was fixed instead. Two lanes run left to right. Your question splits into both. The upper, pink lane is the model: a governed agent server-side writes answer prose. The lower, cyan lane is retrieval: recommendationsFor runs in this browser and returns a stored verbatim span. Both lanes end at one answer card, which shows prose in its upper half and a quoted card in its lower half. The only connection between the lanes is a dashed line from the model's response to the retrieval lane, labelled response.blocked \u2014 it carries a suppress flag and no text. Below a divider, a build-time chain feeds the cyan lane: the CUE fact base, a substring check that fails the build if a quote is not an exact span of its letter, and the stored records shipped in the page bundle. Every box opens a detail card."
    },
    ({ open, setOpen }) => /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("g", { pointerEvents: "none" }, /* @__PURE__ */ React.createElement(
      "text",
      {
        x: "14",
        y: "20",
        fontFamily: "JetBrains Mono",
        fontSize: "9.5",
        letterSpacing: "1.4",
        fill: "var(--text-faint)"
      },
      "RUNTIME \xB7 IN THIS BROWSER, RIGHT NOW"
    ), /* @__PURE__ */ React.createElement("path", { d: "M14 332 L746 332", fill: "none", stroke: "var(--line)", strokeWidth: "1", strokeDasharray: "3 5" }), /* @__PURE__ */ React.createElement(
      "text",
      {
        x: "14",
        y: "354",
        fontFamily: "JetBrains Mono",
        fontSize: "9.5",
        letterSpacing: "1.4",
        fill: "var(--text-faint)"
      },
      "BUILD TIME \xB7 WHERE THE CYAN LANE\u2019S TEXT COMES FROM"
    )), /* @__PURE__ */ React.createElement("g", { pointerEvents: "none" }, /* @__PURE__ */ React.createElement("text", { x: "14", y: "74", fontFamily: "JetBrains Mono", fontSize: "11", fill: "var(--text-mute)" }, "Follow the pink line."), /* @__PURE__ */ React.createElement("text", { x: "14", y: "94", fontFamily: "JetBrains Mono", fontSize: "11", fill: "var(--text-mute)" }, "It reaches the screen."), /* @__PURE__ */ React.createElement("text", { x: "14", y: "114", fontFamily: "JetBrains Mono", fontSize: "11", fill: "var(--text-mute)" }, "It never reaches a name.")), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "q",
        x: 14,
        y: 155,
        w: 138,
        h: 64,
        color: NE,
        title: "YOUR QUESTION",
        sub: "typed into the chat",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("path", { d: "M152 171 C174 171 174 102 192 102", fill: "none", stroke: "var(--text-faint)", strokeWidth: "1.2" }), /* @__PURE__ */ React.createElement("path", { d: "M152 203 C174 203 174 272 192 272", fill: "none", stroke: "var(--text-faint)", strokeWidth: "1.2" }), /* @__PURE__ */ React.createElement(Tip, { x: 192, y: 102, dir: "right", color: "var(--text-faint)" }), /* @__PURE__ */ React.createElement(Tip, { x: 192, y: 272, dir: "right", color: "var(--text-faint)" }), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "agent",
        x: 192,
        y: 70,
        w: 196,
        h: 64,
        color: PK,
        title: "GOVERNED AGENT",
        sub: "server-side \xB7 writes prose",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "prose",
        x: 420,
        y: 70,
        w: 158,
        h: 64,
        color: PK,
        title: "ANSWER PROSE",
        sub: "model-authored text",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("path", { d: "M388 102 L420 102", fill: "none", stroke: PK, strokeWidth: "1.4" }), /* @__PURE__ */ React.createElement(Tip, { x: 420, y: 102, dir: "right", color: PK }), /* @__PURE__ */ React.createElement("path", { d: "M499 134 C499 178 440 178 380 178", fill: "none", stroke: PK, strokeWidth: "1.2", strokeDasharray: "4 4" }), /* @__PURE__ */ React.createElement(Tip, { x: 380, y: 178, dir: "left", color: PK }), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "off",
        x: 200,
        y: 152,
        w: 180,
        h: 52,
        color: PK,
        dashed: true,
        title: "response.blocked",
        sub: "a flag, never text",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("path", { d: "M290 204 L290 240", fill: "none", stroke: PK, strokeWidth: "1.2", strokeDasharray: "4 4" }), /* @__PURE__ */ React.createElement(Tip, { x: 290, y: 240, dir: "down", color: PK }), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "pick",
        x: 192,
        y: 240,
        w: 196,
        h: 64,
        color: CY,
        title: "recommendationsFor()",
        sub: "client-side \xB7 no model",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "span",
        x: 420,
        y: 240,
        w: 158,
        h: 64,
        color: CY,
        title: "THE STORED SPAN",
        sub: "verbatim, not summarised",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("path", { d: "M388 272 L420 272", fill: "none", stroke: CY, strokeWidth: "1.4" }), /* @__PURE__ */ React.createElement(Tip, { x: 420, y: 272, dir: "right", color: CY }), /* @__PURE__ */ React.createElement("path", { d: "M578 102 C598 102 598 126 616 126", fill: "none", stroke: PK, strokeWidth: "1.4" }), /* @__PURE__ */ React.createElement(Tip, { x: 616, y: 126, dir: "right", color: PK }), /* @__PURE__ */ React.createElement("path", { d: "M578 272 C598 272 598 248 616 248", fill: "none", stroke: CY, strokeWidth: "1.4" }), /* @__PURE__ */ React.createElement(Tip, { x: 616, y: 248, dir: "right", color: CY }), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "screen",
        x: 616,
        y: 70,
        w: 130,
        h: 234,
        color: NE,
        title: "WHAT YOU SEE",
        sub: "one card, two sources",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("g", { pointerEvents: "none" }, /* @__PURE__ */ React.createElement(
      "text",
      {
        x: "632",
        y: "146",
        fontFamily: "JetBrains Mono",
        fontSize: "8",
        letterSpacing: "1",
        fill: PK,
        opacity: "0.85"
      },
      "PROSE"
    ), /* @__PURE__ */ React.createElement("rect", { x: "632", y: "154", width: "96", height: "5", rx: "2", fill: PK, opacity: "0.30" }), /* @__PURE__ */ React.createElement("rect", { x: "632", y: "165", width: "86", height: "5", rx: "2", fill: PK, opacity: "0.30" }), /* @__PURE__ */ React.createElement("rect", { x: "632", y: "176", width: "62", height: "5", rx: "2", fill: PK, opacity: "0.30" }), /* @__PURE__ */ React.createElement("path", { d: "M628 198 L734 198", fill: "none", stroke: "var(--line)", strokeWidth: "1", strokeDasharray: "3 4" }), /* @__PURE__ */ React.createElement(
      "text",
      {
        x: "632",
        y: "218",
        fontFamily: "JetBrains Mono",
        fontSize: "8",
        letterSpacing: "1",
        fill: CY,
        opacity: "0.9"
      },
      "QUOTED"
    ), /* @__PURE__ */ React.createElement(
      "rect",
      {
        x: "628",
        y: "226",
        width: "106",
        height: "64",
        rx: "3",
        fill: CY,
        fillOpacity: "0.07",
        stroke: CY,
        strokeOpacity: "0.45",
        strokeWidth: "1"
      }
    ), /* @__PURE__ */ React.createElement("rect", { x: "638", y: "238", width: "86", height: "4", rx: "2", fill: CY, opacity: "0.42" }), /* @__PURE__ */ React.createElement("rect", { x: "638", y: "248", width: "78", height: "4", rx: "2", fill: CY, opacity: "0.42" }), /* @__PURE__ */ React.createElement("rect", { x: "638", y: "258", width: "54", height: "4", rx: "2", fill: CY, opacity: "0.42" }), /* @__PURE__ */ React.createElement("circle", { cx: "643", cy: "276", r: "4.5", fill: "none", stroke: CY, strokeOpacity: "0.55", strokeWidth: "1" }), /* @__PURE__ */ React.createElement("rect", { x: "654", y: "273.5", width: "42", height: "5", rx: "2", fill: CY, opacity: "0.30" })), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "cue",
        x: 14,
        y: 364,
        w: 200,
        h: 60,
        color: CY,
        title: "recommendations.cue",
        sub: "verbatim \xB7 never edited",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("path", { d: "M214 394 L246 394", fill: "none", stroke: CY, strokeWidth: "1.4" }), /* @__PURE__ */ React.createElement(Tip, { x: 246, y: 394, dir: "right", color: CY }), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "gate",
        x: 246,
        y: 364,
        w: 200,
        h: 60,
        color: CY,
        title: "SUBSTRING CHECK",
        sub: "fails the build",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("path", { d: "M446 394 L478 394", fill: "none", stroke: CY, strokeWidth: "1.4" }), /* @__PURE__ */ React.createElement(Tip, { x: 478, y: 394, dir: "right", color: CY }), /* @__PURE__ */ React.createElement(
      DgxBox,
      {
        id: "bundle",
        x: 478,
        y: 364,
        w: 200,
        h: 60,
        color: CY,
        title: "STORED RECORDS",
        sub: "shipped in the bundle",
        open,
        setOpen
      }
    ), /* @__PURE__ */ React.createElement("path", { d: "M578 364 C578 332 330 332 330 304", fill: "none", stroke: CY, strokeWidth: "1.2" }), /* @__PURE__ */ React.createElement(Tip, { x: 330, y: 304, dir: "up", color: CY }))
  ), /* @__PURE__ */ React.createElement("ul", { className: "specag-legend" }, /* @__PURE__ */ React.createElement("li", null, /* @__PURE__ */ React.createElement("span", { className: "specag-sw", style: { "--specag-sw": "var(--neon-cyan)" }, "aria-hidden": "true" }), /* @__PURE__ */ React.createElement("span", null, /* @__PURE__ */ React.createElement("b", null, "Cyan \u2014 text a real person wrote."), " Chosen in this browser from records already downloaded, and rendered exactly as stored.")), /* @__PURE__ */ React.createElement("li", null, /* @__PURE__ */ React.createElement("span", { className: "specag-sw", style: { "--specag-sw": "var(--spec-tone, var(--accent))" }, "aria-hidden": "true" }), /* @__PURE__ */ React.createElement("span", null, /* @__PURE__ */ React.createElement("b", null, "Pink \u2014 text the model authored."), " Rendered as the agent\u2019s own prose, under the agent\u2019s own name. It never appears between quotation marks under somebody else\u2019s.")), /* @__PURE__ */ React.createElement("li", null, /* @__PURE__ */ React.createElement("span", { className: "specag-sw is-dashed", "aria-hidden": "true" }), /* @__PURE__ */ React.createElement("span", null, /* @__PURE__ */ React.createElement("b", null, "Dashed \u2014 the only edge between them,"), " and it points the wrong way to be useful for fabrication: it carries a suppress flag, not a string. The two lanes meet on the screen and nowhere else."))));
  const LEDGER = [
    {
      claim: "The model never chooses who gets quoted.",
      verdict: "Enforced by code path",
      chip: "is-strong",
      tone: "is-enforced",
      how: "The quote block under an answer is produced by recommendationsFor(question) \u2014 a pure function over the records already in the page, keyed on the text the reader typed. The model's reply is not an input to it. There is no prompt instructing the model to behave; there is nothing for it to behave about.",
      where: "spa/components/ChatPage.jsx (the send path) \xB7 spa/components/Recommendations.jsx (recommendationsFor)"
    },
    {
      claim: "The model never authors attributed text.",
      verdict: "Enforced by code path",
      chip: "is-strong",
      tone: "is-enforced",
      how: "The component that renders a quote prints hit.quote.text, and the only place hit comes from is the retrieval above, whose only source is window.SITE_DATA. No assignment anywhere carries a byte of the response body into an attributed string. That is what makes fabrication unrepresentable rather than merely discouraged.",
      where: "spa/components/Recommendations.jsx (RecommendationQuote) \xB7 spa/components/EntityCards.jsx does the same for the project and article cards"
    },
    {
      claim: "A displayed quote is an exact span of what the person wrote.",
      verdict: "Re-checked at render",
      chip: "",
      tone: "is-render",
      how: "The specialization rails re-run the substring test in the browser before drawing anything: a pull quote that is not found inside the stored verbatim text is skipped rather than shown. Every pull quote shipping today passes. The chat's own retrieval does not repeat the test \u2014 it trusts the stored pairing \u2014 so on the chat page this rests on the build gate in the row below, and here it rests on both. Two independent checks, in different places, is the shape worth having: one a reader can run themselves in this page's source, one that stops a bad quote reaching the page at all.",
      where: "spa/components/Specializations.jsx (resolveTestimony: a quote is dropped unless r.text contains q.text) \xB7 resume-core/schema/recommendation.cue"
    },
    {
      claim: "The build fails if a pull quote drifts from the letter.",
      verdict: "Enforced at build",
      chip: "is-strong",
      tone: "is-enforced",
      how: 'gates.CheckRecommendationQuotes compares every pull quote byte-for-byte against the letter it was taken from, and resumecheck exits non-zero if one is not an exact substring \u2014 the deploy runs it before it publishes. Comparison is not normalised: the two mismatches this rule has ever caught were both a straight apostrophe standing in for a curly one, so a checker that folded them would have passed the very failure it exists to find. 19 recommendations, 34 quotes, all verbatim. Until 2026-08-07 this row read "Convention, not enforcement" \u2014 the schema named the gate and the function did not exist.',
      where: "resume-core/internal/gates/recommendationquotes.go \xB7 run by resume-core/cmd/resumecheck (check 8 of 8) via `task resume:verify`"
    }
  ];
  const KIT_CARDS = {
    kind: "cards",
    min: 235,
    title: "The same principle, at production scale",
    note: "Cyan: the parts of agentic-kit whose job is to refuse. Pink: the Command Center systems at PayPal that run on top of that discipline. Nothing here is a measurement \u2014 these are mechanisms, described.",
    source: "Described on the PayPal role and in the agentic-kit, commandcenter-tools and readiness-inventory project records in spa/data.js. No figure is claimed on this grid; the deployed systems are employer-internal.",
    cards: [
      {
        id: "guard",
        tone: "cyan",
        label: "Fail-closed endpoint guard",
        what: "Every tool dispatch passes a guard that denies by default and admits by rule.",
        why: "A permissive default is a governance system that works right up until the first surprise."
      },
      {
        id: "breaker",
        tone: "cyan",
        label: "Circuit breaker \xB7 strike ledger",
        what: "A per-agent, per-session record of injection attempts, budget warnings and schema violations, with an escalating response.",
        why: "Rate limit, then proof-of-work, then suspension \u2014 the response scales with the pattern, not with one bad turn."
      },
      {
        id: "budget",
        tone: "cyan",
        label: "Budget caps \xB7 proof-of-work",
        what: "Spend is bounded per session, and an automated caller is made to pay for its own speed.",
        why: "An agent without a cap will spend without bound. That is not a bug; it is the absence of a design."
      },
      {
        id: "evidence",
        tone: "cyan",
        label: "Hash-chained evidence store",
        what: "Every interaction is journaled, and each entry carries the hash of the one before it.",
        why: "You cannot edit the middle of the record without invalidating everything downstream of the edit."
      },
      {
        id: "expert",
        tone: "pink",
        label: "Expert systems, queried live",
        what: "Service code, declared configuration, docs and runbooks compiled into an artifact a duty officer can question during an incident.",
        why: "Every answer resolves to the line that produced it. Under time pressure, an answer you cannot verify is one you will correctly ignore."
      },
      {
        id: "readiness",
        tone: "pink",
        label: "Readiness inventory",
        what: "Scans the same corpus for failure modes that live in composition rather than in any one file \u2014 thundering herd, retry multiplication, timeout inversion, missing backpressure.",
        why: "No individual file looks wrong, so review never catches them. Finding one while it is still a finding is the whole return."
      },
      {
        id: "writeback",
        tone: "pink",
        label: "Findings written back",
        what: "The readiness findings are written into the expert systems rather than filed as a report.",
        why: "A risk register nobody opens at 03:14 is a document, not a control. The assistant already knows what is fragile before anyone asks."
      }
    ]
  };
  const FORCE = [
    {
      t: "Blocking gate",
      mix: 100,
      what: "The work does not proceed until the check passes. It is the only rung that holds, and the only one whose absence is felt immediately.",
      cost: "Costs the most to build, and every false stop is paid by a human. Reserve it for what must not pass."
    },
    {
      t: "Injected context",
      mix: 62,
      what: "The rule arrives in the harness without anyone asking for it \u2014 an obligation attached to the file being edited, delivered at the moment of the edit.",
      cost: "Cheap and reliable, and it competes for attention with everything else in the window. Speculative injections are how a channel gets skimmed."
    },
    {
      t: "Pulled tool call",
      mix: 32,
      what: "The agent has to decide to ask. When it asks, the answer is exact.",
      cost: "Depends entirely on the agent choosing to reach for it, which is a thing you can encourage and cannot require."
    },
    {
      t: "Passive docs",
      mix: 0,
      what: "The rule is written down somewhere correct.",
      cost: "Advice that requires somebody to go and look is advice that does not happen. It is the floor, not a mechanism."
    }
  ];
  const CLIMB = [
    null,
    "the rule has to be decidable by a program, and somebody has to accept that a false stop is paid for by a person's time. That acceptance is the expensive part, not the check.",
    "the rule has to be attachable to a MOMENT \u2014 something the harness already knows is happening, like a file being opened or an edit landing \u2014 so that nobody has to decide to ask for it.",
    "the rule has to be reachable by a call the agent can make, with an exact answer at the other end. A document is not a call."
  ];
  const FORCE_LADDER = {
    id: "force-of-delivery",
    kind: "ladder",
    title: "Four delivery channels, ranked by force",
    note: "Strongest first. The rungs are ordered by what happens when the rule is not followed, and the gap between two rungs carries what it takes to move a rule up one \u2014 which is the engineering question the ranking exists to answer.",
    source: "Geoff's own ranking, written before this page existed, about the delivery channels inside ONE product rather than about classes of harness across projects. The telemetry that makes it a measured claim is deliberately not on this page, because here it would be supporting a sentence narrower than itself. NO RUNG CARRIES A COUNT AND NO RUNG CARRIES A MEASURED POSITION: the rungs are drawn at equal spacing and the caption under the figure says so. The `to climb` lines are reasoning about the mechanism, in the same category as the cost lines beside them \u2014 nothing in them is a measurement.",
    scaleLabel: "what happens when the rule is not followed",
    rungs: FORCE.map((r, i) => ({
      key: "f" + i,
      label: r.t.toUpperCase(),
      is: r.what,
      cost: r.cost,
      climb: CLIMB[i]
    })),
    steps: [
      {
        id: "top",
        lit: ["f0"],
        say: "Only the top rung holds. It is also the only one whose absence is felt immediately, which is why it is the one teams over-build and the one they most often skip."
      },
      {
        id: "middle",
        lit: ["f1", "f2"],
        say: "The interesting distance is between these two. Both deliver the rule automatically; only one of them arrives without the agent choosing to ask, and that difference is a wiring decision rather than a technical one."
      },
      {
        id: "floor",
        lit: ["f3"],
        say: "The bottom rung is not a mechanism. Advice that requires somebody to go and look is advice that does not happen \u2014 and most governance programmes live here while describing themselves as living at the top."
      }
    ]
  };
  const SKILLS_FANOUT = {
    id: "skills-fanout",
    kind: "fanout",
    title: "One skill source, three harness locations",
    note: "Claude Code and Codex read different paths. One embedded source tree is rendered into all three, so the two harnesses are guided by the same document rather than by two that drift. The edge coming back is the one worth looking at, and it is drawn as what it is.",
    source: "fathom's own skill installer, as described in this section: `fathom init --skills` renders one embedded source tree into .claude/skills/, .agents/skills/ and ~/.codex/prompts/, idempotently and additively, and refuses rather than merges when a file exists and is not fathom-owned. THE RETURN EDGE IS DRAWN UNTERMINATED because that refusal prevents clobbering, not drift: nothing in the design compares the three rendered copies against the source between runs, so a hand-edit to any of them stands until the next run. Stated from the design, not measured \u2014 no drift has been counted, in either direction.",
    direction: "emit",
    origin: { label: "one embedded skill tree", sub: "eight skills, in the binary" },
    forms: [
      { key: "claude", label: ".claude/skills/", sub: "Claude Code" },
      { key: "agents", label: ".agents/skills/", sub: "the harness-neutral location" },
      { key: "codex", label: "~/.codex/prompts/", sub: "Codex" }
    ],
    check: {
      verdict: "none",
      label: "nothing checks this",
      detail: "A re-run restores all three from the one source. Between runs, nothing compares them \u2014 so the guarantee is 'they were written from one source', not 'they still match it'."
    },
    steps: [
      {
        id: "emit",
        lit: ["claude", "agents", "codex"],
        say: "One source, three destinations. This is the half that is easy to state and easy to build, and on its own it guarantees only the first write."
      },
      {
        id: "gate",
        lit: ["check"],
        say: "The return edge has no terminus, and that is the finding rather than a gap in the drawing. Making it a gate is a day's work \u2014 a hash of the rendered tree, compared at session start \u2014 and until that exists, the honest claim is the narrower one."
      }
    ]
  };
  const goChat = () => {
    if (window.GO) window.GO("chat", null);
    else if (window.ROUTE_SET) window.ROUTE_SET("chat");
  };
  const goSpec = (id) => () => window.GO && window.GO("specializations", { specId: id });
  const Tier = ({ v }) => /* @__PURE__ */ React.createElement("span", { className: "specag-tier" + (v === "CHECKABLE HERE" ? " is-here" : "") }, v);
  const SpecAgentic = ({ spec }) => /* @__PURE__ */ React.createElement(SpecPageShell, { spec }, /* @__PURE__ */ React.createElement("style", { dangerouslySetInnerHTML: { __html: CSS } }), /* @__PURE__ */ React.createElement(
    SpecSection,
    {
      title: "How much freedom, and why",
      hint: "three worked examples, one track"
    },
    /* @__PURE__ */ React.createElement("p", { className: "spec-standfirst" }, "How much freedom an agent gets is decided by how repeatable the work is. Below are three systems I built, on one track. The task changes, the shape does not: the more of the process I could settle in advance, the less there is left to constrain at the end \u2014 and where I could settle none of it, the constraint moved to the output. The fence is the whole finding."),
    /* @__PURE__ */ React.createElement(AgenticGradient, null)
  ), /* @__PURE__ */ React.createElement(
    SpecSection,
    {
      title: "Building with agents",
      hint: "two positions, and the rule that picks between them"
    },
    /* @__PURE__ */ React.createElement("p", { className: "spec-standfirst" }, "Two of the three positions live here, and the rule that picks between them is a cost argument. A question whose answer is the same on every project should be answered once, in a function, and never re-decided at a model\u2019s rate. A question whose answer changes every time cannot be answered in a function at all, so what gets written down is the standard, not the answer."),
    /* @__PURE__ */ React.createElement("p", { className: "specag-h" }, "The rule, and its written corollary"),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "The corollary is about ", /* @__PURE__ */ React.createElement("em", null, "delivery"), ": if a rule has to reach an agent, how it reaches it decides whether it holds. I ranked the four channels by force, strongest first.", " ", /* @__PURE__ */ React.createElement("strong", null, "That ranking is mine, and it was written about the delivery channels inside one product rather than about classes of harness across projects \u2014 it is the corollary of the rule above, not the rule itself.")),
    /* @__PURE__ */ React.createElement(VizChart, { data: FORCE_LADDER }),
    /* @__PURE__ */ React.createElement("p", { className: "specag-h" }, "The deterministic harness ", /* @__PURE__ */ React.createElement(Tier, { v: "BUILT \xB7 MY REPOSITORIES" })),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, /* @__PURE__ */ React.createElement("code", null, "fathom init --skills"), " performs eight steps in a fixed order, and there is no turn in any of them at which anything is decided \u2014 because integrating a repository is the same job in every repository. It is idempotent and additive. One canonical operating-contract stanza is templated into both ", /* @__PURE__ */ React.createElement("code", null, "CLAUDE.md"), " and ", /* @__PURE__ */ React.createElement("code", null, "AGENTS.md"), ", marker-delimited, so a re-run replaces exactly that region and nothing else. The skill installer ", /* @__PURE__ */ React.createElement("strong", null, "refuses rather than merges"), " when a file exists and is not fathom-owned. And the exit contract is typed: ", /* @__PURE__ */ React.createElement("code", null, "0"), " wired, ", /* @__PURE__ */ React.createElement("code", null, "1"), " a genuine wiring failure, ", /* @__PURE__ */ React.createElement("code", null, "2"), " wired but the daemon was unreachable \u2014 an operational problem is not a correctness problem and must not be reported as one."),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "Above it sits the fleet layer. Reconcile computes drift, dry-runs by default, and", " ", /* @__PURE__ */ React.createElement("code", null, "--apply"), " applies only the safe subset; structural surgery stays a human decision. Every write carries a receipt holding the prior content, and undo ", /* @__PURE__ */ React.createElement("strong", null, "refuses"), " if anything changed since. All of that machinery exists to make one sentence true:", " ", /* @__PURE__ */ React.createElement("em", null, "advice that requires a human to switch context, find a terminal, and type a command is advice that does not happen. The fix is a button. The design work is entirely in making the button safe.")),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "This is the leftmost position, and it is how a paved road gets written down and installed in a repository \u2014 what a road is ", /* @__PURE__ */ React.createElement("em", null, "for"), ", and what it costs a team not to have one, is argued on", " ", /* @__PURE__ */ React.createElement("button", { type: "button", className: "specag-link", onClick: goSpec("devx") }, "Developer Experience"), " ", "and is not argued again here."),
    /* @__PURE__ */ React.createElement("p", { className: "specag-h" }, "The skills layer ", /* @__PURE__ */ React.createElement(Tier, { v: "BUILT \xB7 MY REPOSITORIES" })),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "One embedded source tree is rendered into three harness locations \u2014", " ", /* @__PURE__ */ React.createElement("code", null, ".claude/skills/"), ", ", /* @__PURE__ */ React.createElement("code", null, ".agents/skills/"), " and ", /* @__PURE__ */ React.createElement("code", null, "~/.codex/prompts/"), " ", "\u2014 so Claude Code and Codex are guided by the same document rather than by two that drift. Eight skills: ", /* @__PURE__ */ React.createElement("code", null, "fathom-onboard"), ", ", /* @__PURE__ */ React.createElement("code", null, "fathom-activate"), ",", " ", /* @__PURE__ */ React.createElement("code", null, "fathom-rewire"), ", ", /* @__PURE__ */ React.createElement("code", null, "fathom-doctor"), ", ", /* @__PURE__ */ React.createElement("code", null, "fathom-plan"), ",", " ", /* @__PURE__ */ React.createElement("code", null, "fathom-verify"), ", ", /* @__PURE__ */ React.createElement("code", null, "fathom-impact"), ", ", /* @__PURE__ */ React.createElement("code", null, "fathom-feedback"), ". They are named in full so the count is countable off the page rather than taken on trust."),
    /* @__PURE__ */ React.createElement(VizChart, { data: SKILLS_FANOUT }),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "What they pin is the ", /* @__PURE__ */ React.createElement("em", null, "grammar"), ", not the answer. A contract is", " ", /* @__PURE__ */ React.createElement("code", null, "{id, symbol, package}"), " and must be grounded against the index", " ", /* @__PURE__ */ React.createElement("strong", null, "before"), " it is written. Skipped work takes a typed disposition \u2014", " ", /* @__PURE__ */ React.createElement("code", null, "refused"), ", or ", /* @__PURE__ */ React.createElement("code", null, "deferred"), " with the trigger that would revive it. The zero value of every key is the strictest contract, so an omission cannot quietly become a weaker claim. The agent still chooses the design; it does not get to choose what counts as a design. And then ", /* @__PURE__ */ React.createElement("em", null, "done means proven"), ": a checked box is a claim, and the gate re-derives it from the index or the box comes off."),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "The gate at the right-hand end of a skills run is only worth what the pipeline running it is worth, and the pipeline is", " ", /* @__PURE__ */ React.createElement("button", { type: "button", className: "specag-link", onClick: goSpec("cicd") }, "CI/CD"), "\u2019s subject; here it matters for exactly one reason, which is that it turns a checked box from a note into a claim."),
    /* @__PURE__ */ React.createElement("p", { className: "specag-h" }, "What the saving actually is"),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "I published a token-saving multiplier on this program once, and retracted it in writing when my own pre-registered benchmark came back under the threshold I had set for it.", " ", /* @__PURE__ */ React.createElement("strong", null, "That is why there is no multiplier on this page."), " The saving here is a mechanism, and the mechanism is countable: a question whose answer is the same on every project is answered once, in a function, and is not re-decided at a model\u2019s rate."),
    /* @__PURE__ */ React.createElement("p", { className: "specag-h" }, "What none of it does"),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose" }, "Guards warn; gates refuse. Hooks fail open by design, so anything that must ", /* @__PURE__ */ React.createElement("em", null, "hold"), " ", "belongs in a blocking gate and nowhere else. A guard exists because the mistake already happened \u2014 speculative guards are the failure mode, because fatigue teaches agents to skim the channel, and a skimmed channel is worth less than no channel. And a passing verify verdict means a test ", /* @__PURE__ */ React.createElement("strong", null, "statically reaches"), " the claimed symbol through the call graph. It never means the test passes, or that it runs at all.")
  ), /* @__PURE__ */ React.createElement(
    SpecSection,
    {
      title: "Building agents",
      hint: "fabrication, made unrepresentable"
    },
    /* @__PURE__ */ React.createElement("p", { className: "spec-standfirst" }, "This is the right-hand case from section 01, at full resolution. Nobody can enumerate the questions a stranger will type, so nobody can encode the process. What ", /* @__PURE__ */ React.createElement("em", null, "can"), " be pinned is what a quoted sentence is allowed to be: a span of stored text, chosen by a function keyed on the reader\u2019s question, rendered from the bundle already in this browser. Follow the pink line below. It reaches the screen. It never reaches a name."),
    /* @__PURE__ */ React.createElement(SpecSignature, { spec }),
    /* @__PURE__ */ React.createElement("div", { className: "specag-try" }, /* @__PURE__ */ React.createElement("div", { className: "specag-try-body" }, /* @__PURE__ */ React.createElement("span", { className: "specag-try-kicker" }, "See it yourself \xB7 30 seconds"), /* @__PURE__ */ React.createElement("p", { className: "specag-try-text" }, "Ask the chat something an assistant would be tempted to embellish \u2014 what do people say about his AI work? What comes back underneath the answer is either a real sentence out of a real letter, or nothing at all. There is no third option available to it, because there is no code path that produces one.")), /* @__PURE__ */ React.createElement("button", { type: "button", className: "btn btn-primary btn-sm specag-try-cta", onClick: goChat }, /* @__PURE__ */ React.createElement(Icon, { name: "sparkles", size: 13 }), "Try to break it")),
    /* @__PURE__ */ React.createElement("p", { className: "specag-prose", style: { marginTop: "18px" } }, "This is the one case of the three you can check without taking anybody\u2019s word for it \u2014 the other two are my account of code in repositories you cannot open, and this one is in the source of the page you are reading. ", /* @__PURE__ */ React.createElement(Tier, { v: "CHECKABLE HERE" }), " The further right a piece of work sits on this gradient, the more of it is left to govern \u2014 who the agent acts as, and what it can be refused, is", " ", /* @__PURE__ */ React.createElement("button", { type: "button", className: "specag-link", onClick: goSpec("governance") }, "Compliance & Governance"), "\u2019s subject, and this page decides only how much there is for it to govern.")
  ), /* @__PURE__ */ React.createElement(
    SpecSection,
    {
      title: "What is actually enforced",
      hint: "four properties, four mechanisms, named"
    },
    /* @__PURE__ */ React.createElement("p", { className: "spec-standfirst" }, "A page whose subject is what a system structurally cannot do has to be the first to say which parts of that are structure and which are habit \u2014 and to keep saying it as the code moves. Row 04 read ", /* @__PURE__ */ React.createElement("em", null, "Convention, not enforcement"), " until 7 August 2026: the schema named a build gate that had never been written. It exists now, so the row changed. A page claiming less than it has is no more accurate than one claiming more."),
    /* @__PURE__ */ React.createElement("ol", { className: "specag-ledger" }, LEDGER.map((row, i) => /* @__PURE__ */ React.createElement("li", { key: i, className: "specag-row " + row.tone }, /* @__PURE__ */ React.createElement("div", { className: "specag-row-head" }, /* @__PURE__ */ React.createElement("span", { className: "specag-n" }, String(i + 1).padStart(2, "0")), /* @__PURE__ */ React.createElement("span", { className: "specag-claim" }, row.claim), /* @__PURE__ */ React.createElement("span", { className: "spec-chip " + row.chip }, row.verdict)), /* @__PURE__ */ React.createElement("p", { className: "specag-how" }, row.how), /* @__PURE__ */ React.createElement("p", { className: "specag-where" }, row.where)))),
    /* @__PURE__ */ React.createElement("p", { className: "specag-src" }, "Counted from the records in spa/data.js: 19 recommendations carrying 34 pull quotes, every one of them an exact substring of its parent text. Arithmetic over the data on this site, not a placeholder \u2014 and not asserted here either: the same count is recomputed on every build by resume-core/internal/gates/recommendationquotes.go, which fails the build rather than reporting a number.")
  ), /* @__PURE__ */ React.createElement(
    SpecSection,
    {
      title: "The same shape, at production scale",
      hint: "mechanisms, not measurements"
    },
    /* @__PURE__ */ React.createElement("p", { className: "specag-note" }, "The same idea, with the stakes raised. In ", /* @__PURE__ */ React.createElement("strong", null, "agentic-kit"), " the answer type makes an uncited answer ", /* @__PURE__ */ React.createElement("em", null, "unconstructable"), " rather than validated: its fields are unexported, there is no setter and no exported literal path, and the one public constructor refuses an empty citation set. Around it, the loop charges a budget before every model call and fails closed; every tool result is screened before it re-enters the transcript, blocking by default, so the raw payload provably never enters; and stop causes are values, not exceptions. ", /* @__PURE__ */ React.createElement(Tier, { v: "BUILT \xB7 MY REPOSITORIES" })),
    /* @__PURE__ */ React.createElement("p", { className: "specag-note" }, "Three agentic systems I built are in production at PayPal, and the expert systems the Command Center\u2019s duty officers query are mine. They are employer-internal. I can tell you what they do and how they are constrained; I cannot show you the code, so no figure is claimed for any of them. ", /* @__PURE__ */ React.createElement(Tier, { v: "FIRST PERSON \xB7 INSIDE AN EMPLOYER" })),
    /* @__PURE__ */ React.createElement(VizChart, { data: KIT_CARDS }),
    /* @__PURE__ */ React.createElement("p", { className: "specag-src" }, "What none of this guarantees, stated because the page would be worth less without it: a schema constrains generation and is not a correctness guarantee, which is why the artifact is re-validated after the call against the same contract that constrained it; injection detection is pattern-based and best-effort, which is why the default action blocks rather than annotates; bounded execution is resource confinement and is not a sandbox. Nothing on this page is measured. The cyan half names files in repositories I wrote; the pink half is my own account of systems that run inside an employer.")
  ));
  window.AgenticSignature = AgenticSignature;
  window.SpecAgentic = SpecAgentic;
})();
